### ISSUE TITLE
Add other missing coding guidelines of odoo

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-tools#106]
There is good guidelines here: 
 - https://doc.odoo.com/es/contribute/15_guidelines/coding_guidelines_framework/
 - https://doc.odoo.com/v5.0/contribute/15_guidelines/coding_guidelines_python.html

We should add someone.

- [x] https://github.com/OCA/maintainer-tools/pull/182
- [x] https://github.com/OCA/maintainer-tools/pull/183

**Comment by Yajo** [comment]
This is fixed, right?

**Comment by pedrobaeza** [comment]
Yeah, closing.
