### ISSUE TITLE
Images in module description not properly displayed on app.store and in the list of local modules in an odoo instance. 

### ISSUE THREAD

**Issue by lmignon** [OCA/maintainer-tools#112]
The module description is the key element to promote our modules. For modules under OCA, the rule is to put this description in a `README.rst` file following some specific guidelines. (https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#modules) 
This file is used by github, odoo and odod.app.store to provide a nicely formatted description of our modules.
When trying to get a nice description of the mis_builder module under all these places I've observed the following problems:
* If you references some images in your description (images stored in static/src/description), even if your file looks fine on github, images are missing in odoo and app.store.
* The licence bagde is not displayed in the app.store

File under github:
![image](https://cloud.githubusercontent.com/assets/544090/9561017/50df23f2-4e34-11e5-85a1-0f2830c8b115.png)

Description in Odoo:
![image](https://cloud.githubusercontent.com/assets/544090/9561021/8e558762-4e34-11e5-916e-5e5478a05b13.png)

Description app.store:
![image](https://cloud.githubusercontent.com/assets/544090/9561026/eeb90f16-4e34-11e5-93d5-ac840d2389e2.png)

The problem for the images is that the rules to be correctly rendered are not the same depending of the target.
* For github the path to the image must be `/static/..../my_img.png`
* For Odoo `/my_module/static/..../my_img.png`
* For app.store `my_img.png`

For the licence badge,  when the file is converted to html5, the image is put directly under the body element and not into a section element. My hypothesis is that the app.store keeps only from the conversion result the 'section' elements (This hypothesis will be verified once https://github.com/OCA/sale-workflow/pull/54 will be merged).

For mis builder, I've solved the problem by manually generating an html description from the REAMDE.rst file. (https://github.com/OCA/account-financial-reporting/commit/6db1e211cc26b2e8a8e55dcce035b9febbe26d06) 
The description is now correctly formatted everywhere.
* ![image](https://cloud.githubusercontent.com/assets/544090/9561142/818ee0dc-4e39-11e5-8ebf-889ff0324b85.png)
* https://www.odoo.com/apps/modules/8.0/mis_builder/

This kind of process can be easily automated and launched in the after_success script by travis but is it really the good solution?

**Comment by pedrobaeza** [comment]
Didn't you find any solution without the HTML?

**Comment by dreispt** [comment]
AFAIK the appstore was build to work with the module `/description` subdir.
But the README at the root of the modules needs different paths.
I feel that we should ask Olivier's involvement, and filing an Issue is probably the best way.

**Comment by pedrobaeza** [comment]
Yeah, we can try that

**Comment by lmignon** [comment]
@dreispt @pedrobaeza For sure, the problems come from Odoo.  I'll fill an issue on Odoo.

**Comment by lmignon** [comment]
issue on Odoo:  https://github.com/odoo/odoo/issues/8300

**Comment by moylop260** [comment]
USING `.. figure::` instead of `image` is fixed.

**Comment by pedrobaeza** [comment]
But it's documented on MT template?

**Comment by eLBati** [comment]
@pedrobaeza I proposed this https://github.com/OCA/maintainer-tools/pull/204

**Comment by pedrobaeza** [comment]
Thanks!
