### ISSUE TITLE
Add docker test for transifex

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-tools#114]
Currently we have a new [Dockerfile](https://github.com/OCA/maintainer-tools/blob/master/Dockerfile-tx-bot) for transifex bot.

I saw that travis now support [docker](http://docs.travis-ci.com/user/docker)

We can add a travis job to build the transifex bot image, self-test, auto docker push to [oca images](https://hub.docker.com/r/ocaimages/txpull/)

Before of work, your feedback is welcome.

The bad news is the time of each travis job: will increase 5 minutes.
The good news is that we can have the image updated, and test it if is working fine.

**Comment by pedrobaeza** [comment]
Transifex is out, so we can close.
