### ISSUE TITLE
Travis fails when author is a unicode string

### ISSUE THREAD

**Issue by clonedagain** [OCA/maintainer-tools#127]
The LINT_CHECK tests of Travis are failing for my PRs because the author contains `u"Numérigraphe"`, which is supported by Odoo but raises an exception during the tests.

Example failure log: https://travis-ci.org/OCA/stock-logistics-warehouse/jobs/80427466#L205

Example PRs affected: https://github.com/OCA/stock-logistics-warehouse/pull/80, https://github.com/OCA/stock-logistics-warehouse/pull/81

**Comment by clonedagain** [comment]
@moylop260 do you think you can tackle this please?

**Comment by yvaucher** [comment]
@clonedagain Shouldn't this issue be on maintainer-quality-tools project ?

**Comment by clonedagain** [comment]
ok moved to https://github.com/OCA/maintainer-quality-tools/issues/248
