### ISSUE TITLE
Feedback hyperlink for issue report

### ISSUE THREAD

**Issue by osvalr** [OCA/maintainer-tools#138]
Currently, for module template edition has a minimal issue, I think. It is hard (and sometimes confusing) to locate all the to-be-replaced fields when creating a new module, the line below shows the current feedback link

```rst
`here <https://github.com/OCA/{project_repo}/issues/new?body=module:%20{module_name}%0Aversion:%20{version}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_.
```

As reStructuredText doesn't keep line break done in raw text and it will be rendered as expected to be. So I suggest something like

```rst
`here <https://github.com/OCA/
{project_repo}
/issues/new?body=module:%20
{module_name}
%0Aversion:%20
{version}
%0A%0A**Steps%20to%20reproduce**%0A%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_.
```

**Comment by nhomar** [comment]
@osvalr make teh PR with the solution please.
