### ISSUE TITLE
Contributing wording

### ISSUE THREAD

**Issue by blaggacao** [OCA/maintainer-tools#144]
I do not or barely understand the following passages of the contributing.md due to syntactical inaccurracies or shortcomings.

> except when compound of module name or object Odoo that is already in the plural

**"Odoo" syntactically wrong at this position, what does the phrase want to express?**

> For models, views and data declarations, split files by the model involved, either created or inherited.

"split files by the model involved, either created or inherited": terrible english, make two phrases or rephrase. eg: "split files so that you have one file per model, no matter if this model is a new or inherited one"

> Filename should only use only [a-z0-9_]

"only" duplicate

> If a function call, dictionary, list or tuple is broken into two lines, break it at the opening symbol. This adds a four space indent to the next line instead of starting the next line at the opening symbol. 
> Example: python partner_id = fields.Many2one( "res.partner", "Partner", "Required", ) 

**"at the opening symbol" (well what's an opening symbol) "at" refers to "before" or "after"? Imprecise.
"instead of starting" better: "instead of identing the next line until the nopening symbol". "identing" is more concise than "starting". Helps understanding.**

> When making a comma separated list, dict, tuple, ... with one element per line, append a comma to the last element. This makes it so the next element added only changes one line in the changeset instead of changing the last element to simply add a comma.

**"This makes it so" - plain wrong english. The whole phrase is completly ununderstanable. Maybe just drop it? Or leave "this habit prevents annoying errors and therby improves your programming efficiency". I don't know, though, if this is what the phrase wanted to express..**

> Action method: an object action method is prefix with action_. Its decorator is @api.multi, but since it use only one record, add self.ensure_one() at the beginning of the method.

"prefix" > "prefixed"

> @api.one method: For v8 is recommended use @api.multi and avoid use @api.one, for compatibility with v9 where is deprecated @api.one.

"is recommended use" "For v8, it is recommended to use" and ", for compatibility with v9, to avoide using @api.one FULLSTOP" "It is deprecated in v9."

A short explenation would be nice, because I was for some reason thinking it is the opposite (might be the same reason why this got relevance to put it there):

> Do not prefix the xmlid by the current module's name (<record id="view_id"..., not <record id="current_module.view_id"...)

:ok_hand:

**Comment by dreispt** [comment]
Those are guidelines for programming topics, so it's quite technical and assumes you are familiar with the terms.
Can you be a little more specific on the inaccuracies?

**Comment by blaggacao** [comment]
It's just plain wrong English, for the upper paragraph. I'm not a linguist, so I lack the words for the specific syntactical error in each situation. This makes it hard to understand and gives room for ambiguity, or at least uncertainty. I try to comment above.

**Comment by dreispt** [comment]
You may like to open PRs to propose the rewording of sentences. You can even do directly from the GitHub GUI.

My advice is to avoid one big PR with many changes. It's best to have a few (maybe by section or closely related paragraphs), so that and issue in one doesn't block merging others where there is an agreement.

**Comment by blaggacao** [comment]
Well, I really do not understand some frases, above. will do a PR for the ones, I understand and mark the ones I don;t above...

**Comment by blaggacao** [comment]
Please clarify the bold statments above, so I can append another PR. Thanks :+1:

**Comment by pedrobaeza** [comment]
This has been moved to https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst, so a PR can be done there.

Closing.
