### ISSUE TITLE
change the objective sentence

### ISSUE THREAD

**Issue by elicoidal** [OCA/maintainer-tools#157]
I would like to move from:
This module was written to extend the functionality of ... to support ... and allow you to ...

to 
This module extends the functionality of ... to support ... and allow you to ...

(more direct and "was written" is awkward while not bringing any information)

**Comment by guewen** [comment]
:+1:

**Comment by osvalr** [comment]
:+1:

**Comment by moylop260** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1: Can you please make the corresponding PR? Or may I?

**Comment by elicoidal** [comment]
@pedrobaeza Can you help me (my github skills suck...)?

**Comment by moylop260** [comment]
@elicoidal 
I will help you

**Comment by moylop260** [comment]
FYI fix here:
https://github.com/OCA/maintainer-tools/pull/162
