### ISSUE TITLE
Question about issue's link in README

### ISSUE THREAD

**Issue by rafaelbn** [OCA/maintainer-tools#200]
HI @OCA/tools-maintainers,

I would like to ask why has been removed in README the link to open issues? It was very useful.

Thanks

Related to https://github.com/OCA/website/pull/221

**Comment by pedrobaeza** [comment]
This is because we can have this text now as template, but it hasn't been done in most of the repositories. I can't find right now the discussion about it.

**Comment by rafaelbn** [comment]
I have checked that if I open an issue in maintainer-tools we get nice format by default, but in other projects like website not. Who could fix this? Thanks

![2016-07-07_9-55-33](https://cloud.githubusercontent.com/assets/8736623/16646201/2284d650-4429-11e6-960a-313838b4e7b1.png)

![2016-07-07_9-56-18](https://cloud.githubusercontent.com/assets/8736623/16646204/28637cb6-4429-11e6-9e8d-2525c51ae2db.png)

**Comment by pedrobaeza** [comment]
Anyone with permissions in the repository

**Comment by moylop260** [comment]
Anyone could create a PR adding .github folder to add the templates like as https://github.com/OCA/maintainer-tools/tree/master/.github

**Comment by gurneyalex** [comment]
I'll try and do something about it.
