### ISSUE TITLE
Cannot set the labels to all repos

### ISSUE THREAD

**Issue by elicoidal** [OCA/maintainer-tools#219]
### Steps to reproduce
1. install the maintainer tools via 
sudo python setup.py install
2. login in github:
eric@eric--XPS-15Z:~/CVS/oca/maintainer-tools$ oca-github-login elicoidal
Password for elicoidal: 
Token stored in configuration file
3. Launch the script
eric@eric--XPS-15Z:~/CVS/oca/maintainer-tools$ oca-set-repo-labels

### Current behavior
the set up seems incomplete and the reasons are not clear, neither how to continue:
Repo account-analytic - Found 3 extra labels
8.0
in progress
7.0
Repo account-budgeting - Found 2 extra labels
8.0
7.0
Repo account-closing - Found 2 extra labels
8.0
7.0
Repo account-consolidation - Found 2 extra labels
8.0
7.0
Repo account-financial-reporting - Found 3 extra labels
8.0
7.0
Pending CLA
Repo account-financial-tools - Found 2 extra labels
8.0
7.0
Repo account-fiscal-rule - Found 2 extra labels
8.0
7.0
Repo account-invoice-reporting - Found 2 extra labels
8.0
7.0
Repo account-invoicing - Found 3 extra labels
8.0
needs tests
7.0
Repo account-payment - Found 3 extra labels
8.0
needs tests
7.0
Repo bank-payment - Found 4 extra labels
CLA Pending
8.0
7.0
approved
Repo bank-statement-import - Found 2 extra labels
8.0
7.0
Repo bank-statement-reconcile - Found 2 extra labels
8.0
7.0
Repo business-requirement - Create 3 missing labels
Traceback (most recent call last):
  File "/usr/local/bin/oca-set-repo-labels", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tools/set_repo_labels.py", line 57, in main
    success = repo.create_label(label_name, all_labels[label_name])
  File "/home/eric/.local/lib/python2.7/site-packages/github3/decorators.py", line 38, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/home/eric/.local/lib/python2.7/site-packages/github3/repos/repo.py", line 683, in create_label
    json = self._json(self._post(url, data=data), 201)
  File "/home/eric/.local/lib/python2.7/site-packages/github3/models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "/home/eric/.local/lib/python2.7/site-packages/github3/models.py", line 121, in _boolean
    raise GitHubError(response)
github3.models.GitHubError: 422 Validation Failed

Repeating the script ends to the same output.

### Expected behavior
all repos are labeled

**Comment by elicoidal** [comment]
@OCA/tools-maintainers

**Comment by elicoidal** [comment]
@pedrobaeza @moylop260 @sbidoul can somebody help?

**Comment by sbidoul** [comment]
@elicoidal there was an existing `Needs Review` label with capital letters. It apparently conflicted with the lower case `needs review` the script was attempting to create. Removing the former allowed the script to create the latter.

**Comment by sbidoul** [comment]
Since the bug occured on the OpenUpgrade too I created #222

**Comment by elicoidal** [comment]
@sbidoul Thanks for the update!
I assume that there is no need for me to relaunch the script

**Comment by sbidoul** [comment]
@elicoidal I ran the script on all repos.
