### ISSUE TITLE
Cannot login via oca-github-login

### ISSUE THREAD

**Issue by elicoidal** [OCA/maintainer-tools#225]
### Milestone (Odoo version)
- 

### Module(s)
oca-github-login

### Steps to reproduce
eric@eric--XPS-15Z:~/CVS/oca$ oca-github-login elicoidal
Password for elicoidal: 
The 'OCA (odoo community association) Maintainers Tools' token already exists. You will find it at https://github.com/settings/applications and can revoke it or set the token manually in the configuration file.
eric@eric--XPS-15Z:~/CVS/oca$ ls
maintainer-tools  oca.cfg
eric@eric--XPS-15Z:~/CVS/oca$ oca-clone-everything
No token has been generated for this script. Please run 'oca-github-login'.
eric@eric--XPS-15Z:~/CVS/oca$ rm oca.cfg 
eric@eric--XPS-15Z:~/CVS/oca$ ls
maintainer-tools
eric@eric--XPS-15Z:~/CVS/oca$ oca-github-login elicoidal
Password for elicoidal: 
The 'OCA (odoo community association) Maintainers Tools' token already exists. You will find it at https://github.com/settings/applications and can revoke it or set the token manually in the configuration file.
eric@eric--XPS-15Z:~/CVS/oca$ ls
maintainer-tools  oca.cfg
eric@eric--XPS-15Z:~/CVS/oca$ oca-clone-everything
No token has been generated for this script. Please run 'oca-github-login'.

### Current behavior
cannot clone oca repository due to the login behavior

**Comment by elicoidal** [comment]
@pedrobaeza @sbidoul is there something I am missing?

**Comment by pedrobaeza** [comment]
You have already make this, but don't write down the corresponding token. You have to go to your account settings, and delete the token for letting this script regenerates it.

**Comment by elicoidal** [comment]
Thanks @pedrobaeza I am not sure about the point of the token (I have not done or added any new token).
If I try to login in: I have an error
if I try without login: I am requested to login in.
I am currently in a blocked situation

**Comment by pedrobaeza** [comment]
Go to your GitHub account and remove the current token:

![seleccion_003](https://cloud.githubusercontent.com/assets/7165771/18804968/172c476c-8203-11e6-86af-fe88ac752537.png)

and then use again oca_github_login

**Comment by elicoidal** [comment]
OK: I have several and didnot which one. thanks!
