### ISSUE TITLE
[WIKI][FIX] Do not export i18n folder of module when migrating to newer version

### ISSUE THREAD

**Issue by atchuthan** [OCA/maintainer-tools#232]
### Milestone (Odoo version)
- 9.0/10.0

### Module(s)
Any OCA module

### Steps to reproduce
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#technical-method-to-migrate-a-module-from-80-to-90-branch. 

### Current behavior
Updates i18n commits to 9.0 and conflicts arises.
Normally, transifex automatically creates file for each branch, so we could skip the export of i18n folder

`git format-patch --stdout origin/9.0..origin/8.0 -- <module path> **':!<module_path>/i18n'** | git am -3`
e.g.
`git format-patch --stdout origin/9.0..origin/8.0 -- magentoerpconnect ':!magentoerpconnect/i18n' | git am -3`

### Expected behavior
no conflict when performing the migration.

Note: created issue after discussing in OCA IRC chat
https://botbot.me/freenode/oca/2016-10-18/?msg=75006135&page=1

**Comment by pedrobaeza** [comment]
Do you have an example of conflictive module migration due to the translations?

**Comment by atchuthan** [comment]
when I tried to fetch the commit history from magentoerpconnect 8.0 to 9.0, I faced this problem due to en_US.po removal @ v9.0

**Comment by pedrobaeza** [comment]
Well, that was something exceptional that was performed once, so no problem in future migrations.

**Comment by atchuthan** [comment]
okay, then I will close my issue.
