### ISSUE TITLE
Merge commit: s/bzr/git + question

### ISSUE THREAD

**Issue by jcdrubay** [OCA/maintainer-tools#233]
### Current Text
While making the merge, please respect the author using the --author option when committing. The author is found using the bzr log command. 

### Suggestion
- `bzr log` should be replaced by `git log`

### Question
- Is it necessary to use the --author? because I imagine the original commit will be merged with the author.

**Comment by pedrobaeza** [comment]
Which file/doc are you talking about?

**Comment by jcdrubay** [comment]
Sorry for not pointing, it is in "OCA guidelines" in the section "review":

 https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#there-are-the-following-important-parts-in-a-review

**Comment by pedrobaeza** [comment]
Ah, thanks for pointing out that old reference. I have change it in https://github.com/OCA/maintainer-tools/commit/94e73614e8979de7df7162b592e1103d01f8e454
