### ISSUE TITLE
FirstName LastName in Reverse Order

### ISSUE THREAD

**Issue by raycollazo** [OCA/maintainer-tools#237]
### Milestone (Odoo version)
- Version 10 Enterprise

### Module(s)
- Firstname Lastname
- 

### Steps to reproduce
1. After Install
2. 
3. 

### Current behavior
We have all of our contacts in as FirstName LastName in the name field. After the Firstname Lastname module is installed, upon edit of contact the module is pulling back the Lastname Firstname in that order. Is there a way to have the module pull back FirstName LastName?
<img width="704" alt="firstnamelastname_ocamodule" src="https://cloud.githubusercontent.com/assets/17937809/20069226/be2c39a6-a4e9-11e6-870b-180fcbe1b410.png">

### Expected behavior

Module pull back FirstName LastName in correct order.

**Comment by pedrobaeza** [comment]
Please put the issue in the proper repository https://github.com/odoo/odoo
