### ISSUE TITLE
Clarification of Many2x field naming

### ISSUE THREAD

**Issue by Fenkiou** [OCA/maintainer-tools#246]
In the guidelines, we can read:

> Since new API works with records or recordsets instead of id lists, don't suffix variable names with _id or _ids if they do not contain an ids or lists of ids.
>     ...
>     res_partner = self.env['res.partner']
>     partners = res_partner.browse(ids)
>     partner_id = partners[0].id

And:

> One2Many and Many2Many fields should always have _ids as suffix (example: sale_order_line_ids)
> Many2One fields should have _id as suffix (example: partner_id, user_id, ...)

So what should we follow ? I prefer the first proposal because it make more sense to me.

**Comment by lasley** [comment]
These are two different concepts. The first is for the naming of field declarations, and the second is for naming of variables that are recordsets.

Using _id and _ids in the variable names creates an ambiguity of what the variable is representing. Not adding them to the field declarations, however, breaks good db design practice.

— Dave Lasley
 <https://laslabs.com/>

**Comment by Fenkiou** [comment]
Oh ok, coming from Django, I never wrote a relational field suffixed with _id because Django do it itself (just searched this right now).

So for me, it was awkward in Odoo to write this as it was not really an id but an object.. But ok, now I understand why we do this.
