### ISSUE TITLE
Proposal to strip odoo version since that is added by default

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-tools#256]
We are using the [following guideline for module manifest version](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers):
 - `odoo_version.breaking.feature.fix`

Odoo append `odoo_version` by default - [openerp/modules/module.py#L368](https://github.com/odoo/odoo/blob/da3e6e36e6c8cbdb88c18229cc58c637357c6427/openerp/modules/module.py#L368)

![screen shot 2017-01-18 at 10 47 53 am](https://cloud.githubusercontent.com/assets/6644187/22073413/e6eb60d8-dd6a-11e6-8520-240ad90a1279.png)

The main reason to append custom version was because odoo is not append `odoo_version` like as comment: https://github.com/OCA/maintainer-tools/pull/90#issue-97329423 by @dreispt 

> This is so because in the past Odoo/Openerp automatically added the major version to module versions. Thus if your module was version "6.1.1", it would be displayed as "6.1.6.1.1".
It is no longer the case: [now](https://github.com/odoo/odoo/blob/8.0/openerp/modules/module.py#L368) Odoo does not do that if the major version is already appended to the module version!

Maybe was a issue from odoo and later fixed.

After that we have other good reason to still use manual `odoo_version` from manifest module version?

**Comment by sbidoul** [comment]
@moylop260 setuptools-odoo relies on that to determine the Odoo series. It is possible to add it manually in setup.py but that is more work. So I vote to keep it as is.

**Comment by pedrobaeza** [comment]
It's not only that. We decide to make this for knowing for which version the module was thought. Imagine you have a module in a repo that is not ported for 2 versions. Without that, you don't know if the existing code is from the previous version or for 2 versions ago.

**Comment by lasley** [comment]
We also have the issue of decrementing version numbers to consider. If we don't keep the Odoo version, we'll be resetting to a literal version 1 every migration. As it is now, we are keeping with sym ver by resetting all digits on the right when one on the left is changed.

**Comment by moylop260** [comment]
> It's not only that. We decide to make this for knowing for which version the module was thought. Imagine you have a module in a repo that is not ported for 2 versions. Without that, you don't know if the existing code is from the previous version or for 2 versions ago.

Do you have the comment related with these reasons? (I didn't find it)

For OCA projects currently we are using the name of the branch to know the version of the modules plus `installable` flag from manifest.
If you have a branch `10.0` with a manifest `installable: False` then that module is not migrated for odoo 10.0 version yet.

**Comment by lasley** [comment]
@moylop260 - There are some good examples in vertical-medical, here is [one](https://github.com/OCA/vertical-medical/blob/10.0/oemedical_icu/__manifest__.py). I can tell you that this module was from version 7, but most others would not know that.

**Comment by moylop260** [comment]
I got it
If I have a module
`installable: False` with manifest `version: '6.1.x.y.z'` in the branch `10.0`
I can see if this module wasn't touched from `6.1` odoo version

Right?

**Comment by lasley** [comment]
Exactly! I know for me at least, this is a great means of resource estimation without having to dive deep in the code.

**Comment by moylop260** [comment]
Thanks for reply.

You touch other important matter about reset version if a migration is created.
Maybe you want open other thread about in order to add this documentation and avoid discuss in each PRs
