### ISSUE TITLE
twitter oca bot

### ISSUE THREAD

**Issue by bealdav** [OCA/maintainer-tools#258]
Just an idea.

### Steps to reproduce
Subscribe to twitter ocabot

### Current behavior
all transiflex upgrade create a tweet as any code update. If you're only interested by code changes it s a problem.

### Expected behavior
split oca bot in 2 twitter account to only subscribe to code changes not translation. 

I don't know if it's easy or difficult to do.
Thanks to evaluate. :-)

**Comment by pedrobaeza** [comment]
I'm afraid this is not possible, as the service is something provided by GitHub, and we have no control over it.

The only possibility we have is to see if there's any option to include text in the commit to skip the tweet.

**Comment by bealdav** [comment]
Transifex is the text inside the commit, isn't it ?

**Comment by pedrobaeza** [comment]
The tweets are put by GitHub itself, so unless there's any way to tell GitHub to not post tweets in certain conditions, we can't do any other thing.

**Comment by lasley** [comment]
Maybe something to the `github-connector` to provide this functionality instead?

**Comment by pedrobaeza** [comment]
This can't be done as stated, and no text filter possibility, so we have to stick to this. On contrary, other may consider valuable to have also those commits reported, and more now that Weblate commits with the author and with more frequency.
