### ISSUE TITLE
Contributing.md and module structure: 'templates' subdirectory

### ISSUE THREAD

**Issue by LeartS** [OCA/maintainer-tools#259]
[The directories subsection](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#directories) of contributing.md doesn't use the `templates` directory; it says that the `views` one "contains the views and templates, and QWeb report print templates"

And yet, immediately after in the same document, the `templates` folder is mentioned in 2 times, I also see that a lot of OCA modules have it.

So, what's the consesus on this? Should we put qweb templates with the standard backend views in `views`, or should we create the specific subdirectory?

**Comment by lasley** [comment]
Good point @LeartS - there's definitely mixed signals here. I think `templates` is the legacy form, and the docs just weren't updated. 

My vote's on just a `views` folder if nobody remembers the history.

**Comment by dreispt** [comment]
Odoo [official guidelines](https://www.odoo.com/documentation/10.0/reference/guidelines.html) state that templates go into the `/views` directory.
Where stated otherwise should be fixed accordingly.

**Comment by pedrobaeza** [comment]
It seems that `views` is the proper one, so I close.
