### ISSUE TITLE
How to migrate a module that is not present in last branch but that is present in previous branch

### ISSUE THREAD

**Issue by invitu** [OCA/maintainer-tools#261]
In order to make the review easier for maintainers, it understood that migrating a module that is not present in the last branch should be done with cherry-picking or with 2 Steps (Adding the module then migrating the module)
See @legalsylvain comment here https://github.com/OCA/pos/pull/154#issuecomment-282669089
and @lasley comment here https://github.com/OCA/partner-contact/issues/309#issuecomment-283148535

What is best practise ?

**Comment by lasley** [comment]
@invitu The current practice is to use the [migration instructions](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#howto), which performs the cherry picks that @legalsylvain was referring to.

**Comment by dreispt** [comment]
Answered, I believe.
