### ISSUE TITLE
Suggestion for migration wiki

### ISSUE THREAD

**Issue by lasley** [OCA/maintainer-tools#273]
In the migration wiki, I suggest that we add a note about switching the `installable` key to `True` as one of the migration steps.

**Comment by dreispt** [comment]
Go ahead!

**Comment by lasley** [comment]
Honestly I would have just done it, but I'm not a PSC here so I don't have edit rights 😉

**Comment by max3903** [comment]
Done:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#tasks-to-do-in-the-migration
