### ISSUE TITLE
[RFC] Change the copyright link in python files headers

### ISSUE THREAD

**Issue by elicoidal** [OCA/maintainer-tools#278]
### Current behavior
current link in the headers is:
```# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).```
While in the README file it is: http://www.gnu.org/licenses/agpl-3.0-standalone.html

### Expected behavior
I suggest to harmonize both link to the same target: http://www.gnu.org/licenses/agpl-3.0-standalone.html

**Comment by elicoidal** [comment]
@OCA/core-maintainers

**Comment by pedrobaeza** [comment]
OK for me, but I prefer the more generic one, as we talk about AGPL-3 or later, so if an AGPL-4 appears, the link won't be correct.

**Comment by elicoidal** [comment]
I am fine as long as we are consistent over all files

**Comment by leemannd** [comment]
Totally in favour of being more consistent. I made a PR in order to update this. As @pedrobaeza says, it is best to take the more generic link.
