### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by kenvac** [OCA/maintainer-tools#283]
### Milestone (Odoo version)
- 8.0

All travis build related to version 8 branch is failing as it could not find requirements.txt file.

E.G
https://travis-ci.org/OCA/OCB/builds/254475694

requirements.txt no longer available at location ${HOME}/maintainer-quality-tools/travis/requirements.txt
It has been move to root directory ${HOME}/maintainer-quality-tools/requirements.txt

**Comment by pedrobaeza** [comment]
This should go in maintainer-quality-tools, not here. Please report it there.
