### ISSUE TITLE
svg link is wrong renderized in rst files

### ISSUE THREAD

**Issue by cubells** [OCA/maintainer-tools#286]
As SVG does not work from READMEs by design for security concerns, when you read module information you see that screen:

![seleccio_323](https://user-images.githubusercontent.com/4386443/29959873-a908d03e-8ef9-11e7-8c5f-df92d36c7faf.png)

but I think It's important license to be seen clearly as It's shown here:

![seleccio_324](https://user-images.githubusercontent.com/4386443/29959919-d9f2c916-8ef9-11e7-8c98-9b60aeccf261.png)

The problem is first line in https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst file:

`.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg`

Possible workarounds are change that line by:

`.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg?`

or simply:

`.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.png`

**Comment by pedrobaeza** [comment]
The problem is that SVG is not rendered or incorrect link?

**Comment by cubells** [comment]
The problem is that svg is not rendered.

**Comment by pedrobaeza** [comment]
Then the only solution is to switch to PNG, but there's a lot of modules with that in SVG already...

**Comment by elicoidal** [comment]
Agree with the solution.
Can we script the change with a sed function? (one time)

**Comment by elicoidal** [comment]
By the way same happens with the logo of the OCA in the credits

**Comment by pedrobaeza** [comment]
Have you checked if v11 will support SVG?

**Comment by elicoidal** [comment]
we should maybe want to switch to something like 
```
` * Odoo Community Association: `Icon <https://odoo-community.org/logo.png>`_
```

This is not a problem of Odoo IMO but rst format no?

**Comment by pedrobaeza** [comment]
Is odoo "HTML viewer" that is not rendering SVG. Look how GitHub/your browser does it correctly.

**Comment by cubells** [comment]
@pedrobaeza 

I don't know if it's problem of html viewer of odoo. 

Github solve the problem here: https://github.com/github/markup/issues/556

**Comment by elicoidal** [comment]
True: we might be Odoo compliant but still not rst compliant which is not optimum.
We generate [documentation](https://oca-doc.elico-corp.com) from the README via readthedoc and the image do render properly.
So for me the issue is minor (although do think png might bring less issues over time)

**Comment by pedrobaeza** [comment]
Being more exact, it can be the RST to HTML converter, not the HTML viewer itself.

**Comment by elicoidal** [comment]
on the other hand, rst2pdf does not render the image

**Comment by pedrobaeza** [comment]
This has been changed on templates, so I close. I like more SVG (and I introduced SVG support in image widget in v12), but this will probably continue the same on the HTML viewer.
