### ISSUE TITLE
Wiki doc - migration instruction

### ISSUE THREAD

**Issue by bealdav** [OCA/maintainer-tools#296]
### Milestone (Odoo version)
- V10

### Current behavior
V10 doc is overcomplicated https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch 
compared to 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#technical-method-to-migrate-a-module-from-80-to-90-branch

V9 procedure works. 

### Expected behavior
- Update wiki v10 like v9 'technical method'

What do you think ? @pedrobaeza @sbidoul 
Thanks

**Comment by pedrobaeza** [comment]
I "complicate" it because some steps were supposed to be known by the reader, and there were questions about how to clone and so on (for git beginners), but if you think it's more difficult or it's too verbose, we can remove it.

**Comment by bealdav** [comment]
OK I understand, then we could have: normal procedure and short procedure. Thanks for your work.

**Comment by pedrobaeza** [comment]
OK, Wiki page modified with dual instructions:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
