### ISSUE TITLE
Group: OCA.Contributor Access rights for labels and/or milestones

### ISSUE THREAD

**Issue by leemannd** [OCA/maintainer-tools#310]
As a member of the OCA/contributor's group I cannot put a label nor a milestone on my PR.
I didn't knew it was a goal behind creating the "contributor" group, but indeed I would be happy to manage labels on my PR's. I learned it [there](https://github.com/OCA/maintainer-tools/pull/309) .

So if you're in the process of adding this possibility I'll be happy.
Up @pedrobaeza @lasley @sbidoul

**Comment by sbidoul** [comment]
Unfortunately I don't think github permission system is fine grained enough us to give these rights to the Contributors group without giving write access to the repository. I may have overlooked somthing though.

**Comment by lasley** [comment]
Yeah actually I meant to assign this one to myself. I think your eval is correct @sbidoul, but I plan on exploring a bit more - I think I remember something about a fine-grained permissions system being introduced recently

**Comment by pedrobaeza** [comment]
This is what I have found about that:

https://github.com/blog/2064-new-organization-permissions-now-available
https://github.com/blog/2020-improved-organization-permissions

**Comment by lasley** [comment]
Furthering that research:
* https://help.github.com/articles/repository-permission-levels-for-an-organization/

Welp that sucks. I guess that highlights the need for #203 

I'm going to close this with a ☹️  - thanks for creating the issue so we could have the research in context for historical reference @leemannd
