### ISSUE TITLE
How to customize homepage from odoo 10 to Odoo 11

### ISSUE THREAD

**Issue by BINHNGUYEN2512** [OCA/maintainer-tools#311]
### Milestone (Odoo version)
- Odoo 11

### Module(s)
- 
- Theme/Website

### Steps to reproduce
I want to change homepage from Odoo 10 to odoo 11
### Current behavior
There are some difference in odoo 10 to odoo 11, 
Website_templates.xml in odoo 11 is not included in the Homepage like odoo10
It has moved to website_data.xml 

### Expected behavior
I try to write when installing it's got issue
<?xml version="1.0" encoding="utf-8" ?>
<odoo>
    <template name="Home" id="website.page" page="True">
          <t t-call="website.layout">
                <div id="wrap" class="oe_structure">
issue is:
AssertionError: Element odoo has extra content: template, line 3

**Comment by dreispt** [comment]
Hi, this looks like a generic technical question about Odoo, and not specifically about this project.
I suggest you to ask this on an Odoo mailing list.
