### ISSUE TITLE
.deb packaging for modules

### ISSUE THREAD

**Issue by hveficent** [OCA/maintainer-tools#320]
# .deb packaging for modules
We intend to define a process to package all OCA modules as DEB packages, as this is the default tool to manage the software lifecycle in Debian-based environments.

Our intention is to build a process on top of the work that is already done to package modules in pip. As a consequence the naming convention for packages would be:

For python 2 (Odoo versions up to 10):
python-odoo<major version>-addon-<module-name>_[8|9|10|11].0.x.y.z.99.devN_all.deb, N being the number of git commits since the version change.

For python 3 (Odoo versions up to 10):
python3-odoo<major version>-addon-<module-name>_[8|9|10|11].0.x.y.z.99.devN_all.deb, N being the number of git commits since the version change.

## **Repository:**

OCA would provide a repository  http://nightly.odoo-community-org.com, similar to https://nightly.odoo.com.
Every night a new set of packages would be created for each OCA repository or branch. The set would consist of deb package for Debian distribution.

### **Usage:**

The user would first install odoo from deb package, as described in https://www.odoo.com/documentation/11.0/setup/install.html#repository

A user would execute the following commands as root:
```
wget -O - https://nightly.odoo-community.org/odoo-community.key | apt-key add -
echo "deb http://nightly.odoo-community-org.com/11.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo-
community.list
```
Then, just with a simply: 

``$ apt-get install <package_name> ``
or 
``$ dpkg -i <package_name> ``

user would be able to install the module.

This would make all the OCA deb packages available for install.

[ ] Create domain nightly
[ ] Create public key (PGP) odoo-community.key
[ ] Publish OCA public key on pgp.mit.edu or alike

## **Process to create deb packages**

In order to create packages for all repositories and versions, we would need a nightly process. Find below a first approximation to the steps that the script would be required to perform.

 I’ve started testing using setuptools-odoo as our colleagues ACSONE use to pack wheels of all OCA modules.

### **Usage/Requirements:**

```
$ sudo apt-get -y install build-essential debhelper tar gzip devscripts
$ pip install --upgrade pip setuptools stdeb argparse # upgrade modules
$ git clone https://github.com/acsone/setuptools-odoo.git 
$ cd setuptools-odoo
$ python3 setup.py install # Install setuptools-odoo using setuptools
$ pip3 freeze | grep setuptools-odoo # setuptools-odoo==2.0.2
```

My procedure was next:

```
$ cd <repository>/setup/<module_name>/
$ python setup.py --command-packages=stdeb.command sdist_dsc # generate dist packages
$ cd deb_dist/odoo<version>-addon-<module_name> 
$ env DEB_BUILD_OPTIONS=nocheck debuild -us -uc # generate .deb file avoiding tests
```

If I tried to use odoo version 10 I had the same issue as https://github.com/odoo/odoo/pull/15718

- [FIX] workaround setuptools >= 31 creating the odoo package before import odoo #15718

So I’ve moved to 11 to continue.

See https://pastebin.com/wmg6EvB8 for details on the logs generated by this procedure.

## **Known issues**

- setuptools-odoo
    - Similar to what is defined by setuptools-odoo https://pypi.python.org/pypi/setuptools-odoo
    - Way to reuse this module to generate dependencies properly.
        - Module_A requires Module_B, installing Module_A: Module_B is installed as a dependency if is not in the system yet.
        - External python dependencies
- Auto-generate gpg signatures to verify packages from debian repository and properly licence/copyrights.
- ...

**Comment by blahmutz** [comment]
that would be great! i dont like to mess around with pip on a productive system. If i could use .deb (apt, aptitude etc.) that would be such a nice thing!

**Comment by dreispt** [comment]
Is this related?:
https://twitter.com/realForkSand/status/987393480681865217

**Comment by pedrobaeza** [comment]
How is the progress on this? Can we close?
