### ISSUE TITLE
Update wiki "Migration to version 11.0" with cron updates

### ISSUE THREAD

**Issue by simahawk** [OCA/maintainer-tools#322]
## To add
If you create `ir.cron` in module setup you have to change:

* `model` (string) -> `model_id` (m2o to model)
* `function` (string) + `args` (string) -> `code` (eg: model.cron_that_does_something())

**Comment by simahawk** [comment]
@pedrobaeza I did not find any good way to edit wiki: posting here ;)

**Comment by dreispt** [comment]
I made the edit at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by simahawk** [comment]
@dreispt any chance we  can make more "accessible"? What about a doc folder + GH pages?

**Comment by pedrobaeza** [comment]
I'm afraid GitHub doesn't offer that, and changing to docs + GH pages seems a bit bloated for something easy like this, where this is the first issue for changing something in years.

**Comment by dreispt** [comment]
@pedrobaeza Yes indeed. In this case it would have been easier for everyone to have a PR.
What do you think about having a specific repository to hold OCA technical and reference documents, such as OCA/docs?

**Comment by simahawk** [comment]
on one hand I agree w/ you, OTOH this is a barrier for contributions.
Plus, honestly this page - as some others - is not really human-friendly for readability.
IMO we should move to something that boost collaboration and allow ppl to improve the whole thing.

Moving to `OCA/docs` sounds a good thing for the future but maybe we can start w/ a simple `docs` folder in this repo?
An example from Plone community: https://github.com/plone/documentation -> https://docs.plone.org/

**Comment by sbidoul** [comment]
:+1: for OCA/docs. Actually a fair share of the OCA website would be best managed as a sphinx documentation (eg the whole How to contribute / resources part, which could merge with contributor guidelines currently hosted in github). I'm convinced it would really boost collaboration and improve it's overall quality.

**Comment by pedrobaeza** [comment]
OK, go ahead with it.

**Comment by sbidoul** [comment]
@dreispt as you are working on the website menu structure, what do you think of moving (part of) the website to a Sphinx documentation? 

@elicoidal as you do a lot of Sphinx doc, your input would be valuable too.

**Comment by elicoidal** [comment]
@sbidoul I agree that most of the "technical" part of the website (I mean the on marketing side) could be easily replaced by content hosted in github+rst.
We should identify what should be part of this doc but mostly Resource + Contribute + Association Menus
