### ISSUE TITLE
JS code guidelines in conventions?

### ISSUE THREAD

**Issue by hbrunn** [OCA/maintainer-tools#323]
most of our multi contributor javascript files look horrible because everyone uses their way of indentation and brace placement. I'd suggest to stick to something that validates most of the existing code and write this in the conventions, which would be https://en.wikipedia.org/wiki/Indentation_style#Variant:_Java I guess.

I personally like a mix of BSD and K&R style:

```javascript
TheClass.include({
    a_function: function()
    {
        while(something)
        {
                somethingChainableDefferredObjectForExample().then(function(a)
                {
                })
                .then(function(a)
                {
                });
        }
    }
})
```

But that's a digression, let's write Java in the conventions and be done with it.

If I didn't make a mistake, the above example then should be

```javascript
TheClass.include({
    a_function: function() {
        while(something) {
                somethingChainableDefferredObjectForExample().then(function(a) {
                }).then(function(a) {
                });
        }
    }
})
```

and spacing rules as PEP8 says, right?

**Comment by pedrobaeza** [comment]
@Yajo what do you think about this?

**Comment by Yajo** [comment]
I completely agree. I feel the same quite often, but don't have a basis, such as we have PEP8 in Python, to say "don't write like this".

I only want to add that, from the 2 examples form @hbrunn, I'd agree more on the 2nd.

Also I want to ask my friend @kutyel, who can lead us to some style guides too for sure, so we can choose.

As a final point, I also think we must force those guidelines through [our ESLint template in pylint-odoo](https://github.com/OCA/pylint-odoo/blob/master/pylint_odoo/examples/.jslintrc) and start popping a :x: in Travis when not met. @moylop260 will know better how can we do that.

**Comment by moylop260** [comment]
Could you review if there is a rule from https://eslint.org/docs/rules after that you can enable it from our [our ESLint template in pylint-odoo](https://github.com/OCA/pylint-odoo/blob/master/pylint_odoo/examples/.jslintrc)

**Comment by Yajo** [comment]
Yep, it seems that template is the best way to go for now.

Is that linter now required? I'm seeing :x: in https://github.com/OCA/web/pull/940 for that...

**Comment by pedrobaeza** [comment]
This has been implemented right now through the linter, so I close.
