### ISSUE TITLE
Migration of modules from odoo 7.0 to odoo 8.0

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-tools#33]
Hello all,
(Advance apologies if this is not the right place for this issue)

As you know, there's a new 8.0 version and there to do a job migration python modules type grep-replace. 
We are to work on this matter. 
I would like to share our work with the OCA. 

I need to know which is the right place to push this type of script.

**Comment by dreispt** [comment]
@moylop260 Is this an active discussion or should it be closed?

**Comment by moylop260** [comment]
@dreispt 
I'm working in oca-autopep8 to migration script's.
https://github.com/OCA/maintainer-tools/pull/105
Then we can close this issue
