### ISSUE TITLE
Proposal: versionless branches

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-tools#334]
### Milestone (Odoo version)

Upcoming 12.0+

### Module(s)

all 

### Current workflow

Actually we have to maintain separate branches for all Odoo versions. This involves a big work about migrating addons from version n to version n+1, and when patches land in several supported versions, we have to open several PRs with several revisions, etc.

### Proposed workflow

IMHO we should start from next Odoo version to avoid affecting current workflow, the upcoming 12.0, and start a new `master` branch in each repo, that will keep the addons from now on, no matter the Odoo version.

- From that version, the usual Pythonic workarounds to work with several versions of packages should start to happen. Example:

  ```python
  try:
      import openerp as odoo  # Stupid example, no more `openerp` needed since Odoo 10, but just so you get the point
  exception ImportError:
      import odoo
  ```

- Migration scripts can either be into folders like `migrations/12.0.1.2.0` or like `migrations/1.2.0`, depending on if the migration affects the Odoo release upgrade, or the addon itself upgrade.

- Travis jobs could be triggered against all supported versions at once by defining its matrix.

- Unit tests can make use of [`skipIf`](https://docs.python.org/3/library/unittest.html#unittest.skipIf) and [`skipUnless`](https://docs.python.org/3/library/unittest.html#unittest.skipUnless) decorators if they belong to specific odoo versions.

- When adding support for newer versions, those should be considered the *default* addon version, and old-specific stuff should land in blocks such as:

  ```python
  if odoo.release.version < "14.0":
      # Specific Odoo 12 stuff
  if odoo.release.version == "12.0":
      ...
  ```

IMHO this would be a big leap forward in the maintainability of OCA addons. After all, we maintain addons, not Odoo itself (except for OCB, of course).

**Comment by pedrobaeza** [comment]
I don't see this, as each version has very different functional and technical code, so maintaining a module compatible for all versions is almost impossible...

**Comment by sbidoul** [comment]
That would be nice indeeed in areas where Odoo is relatively stable. There would be some hurdles though.

A few thoughts:

- we'd need a mechnism to declare supported Odoo versions in the manifest (perhaps Odoo could add it?)
- what about release-conditional code in JS?
- what about release-conditional code in XML views?

Perhaps we could experiment before 12 by enabling the master branch for some repos and see what the impact who be on the various toolchains.

**Comment by pedrobaeza** [comment]
@sbidoul making a functional change on the module means to check that change on all the supported versions. That's something simply not feasible.

**Comment by sbidoul** [comment]
It is feasible for some modules. I do it for mis builder for instance. Many modules in accounting and server-tools would work unchanged from 9 to 11. 

Testing across versions is more work for maintainers, that's for sure. But with the current situation we have features or fixes appearing randomly in any version and not being ported. People get bitten by that. So there is a cost too.

So this idea is certainly not trivial to implement and is not applicable everywhere, but I would not dismiss it as impossible right away.

**Comment by pedrobaeza** [comment]
OK, I prefer not to do that, but if the whole maintainers of something like mis_builder decides to try this approach... Everything is built around the whole version numbers, so first thing to deal is with that (the MQT check, branch name for testing, etc...).

**Comment by Yajo** [comment]
@sbidoul you nailed it! I think those would be the real problems, since for Python the thing is solved. Even if the addon is extremely different (Python-side), the code could even look like:

```python
if odoo.release.version < "14.0":
    from . import models_13_0
else:
    from . import models
```

So the real problem is the JS, manifest and data files.

> we'd need a mechnism to declare supported Odoo versions in the manifest (perhaps Odoo could add it?)

I'm not sure but I think that you can set the keys you want in the manifest. Another thing would be if they are or not processed by Odoo. We can add a decorator to `oca.decorators` that helps us decorate the `pre_init` and `pre_update` hooks to auto-check if the version is supported when installing or upgrading, and to raise an exception if not.

That would be just the least dirty workaround in case Odoo doesn't add support for such feature, but I think they will like it and add it if a proper PR is sent to master.

> what about release-conditional code in XML (views, data)?

I think the `<data>` element (and [its friends](https://github.com/odoo/odoo/blob/e6fd9ccdf0518e82312cdac21f06430d145acda5/odoo/import_xml.rng#L301-L303)) would need to support a couple of new attributes, such as `version_min` and `version_max`.

So you can do:

```xml
<data>
  <!-- Only for Odoo 12.0 -->
  <data version_min="12.0" version_max="12.0">
    <record>...</record>
  </data>

  <!-- Only for Odoo >= 13.0 -->
  <data version_min="13.0">
    <record>...</record>
  </data>

  <!-- Common stuff -->
  <record>...</record>
</data>
```

> what about release-conditional code in JS?

This case would fall under the same as the above one:

```xml
<data>

  <data version_min="14.0">

    <template id="assets_common" inherit_id="web.assets_common">
      <xpath expr=".">
        <link rel="stylesheet"
              href="/module/static/src/css/module_name_14_0.css"/>
        <script type="text/javascript"
                src="/module/static/src/js/module_name_14_0.js"/>
      </xpath>
    </template>
  </data>
</data>
```

> Everything is built around the whole version numbers, so first thing to deal is with that (the MQT check, branch name for testing, etc...)

Some changes would be needed here too indeed. Let me ping @moylop260 who is one of the biggest experts on MQT I think. Do you think this point would be too difficult?

---

So it seems we are 2 small PRs away from being able to do all of this. IMHO it would be a huge step forward on OCA's maintainability!

Please let me take the freedom to ping @odony and @mart-e, to invite them to share their vision on the subject. Maybe odoo has some hidden or planned feature that could serve for us in this matter?

Thanks everyone!

**Comment by Yajo** [comment]
After upstream discussion, it's clear that this one is a lost battle. 🙁 Our only chance is to stop supporting official fork and only support OCB, which I feel is another lost battle. I hope some day someone provides a solution that fixes the problems outlined in https://github.com/odoo/odoo/pull/25371#issuecomment-401382654, at least I did all I could.

**Comment by yelizariev** [comment]
This approach can be partially applied, while keeping current structure of repositories.
So, instead of making few pull requests with different code, you can prepare a single PR and let robots make others PRs.
I kind of use it, but instead of code that checks odoo version, I make a comment like

```
import openerp as odoo
# In Odoo 10.0 use following:
# import odoo
```
So, I make a PR to 9.0, then it's merged, me or a robot move the code to v10 and then I update the code according to existing comments without thinking about it much.

For python and maybe js it can be easily automated by checking odoo version. For xml this requires updates in odoo framework.

**Comment by sebastienbeau** [comment]
@Yajo just some feedback from repo where I am PFC (storage, search engine)
I am convinced that this can not be applied to all repo (because some repo are a mix of a lot of different module and migration process is a opportunity to drop obsolete module)
But in some repo (like search-engine, storage, connector, queue_job @guewen ) where all module are really linked together and don't depend of a lot other module, I think it will be great to avoid having one branch per version (We can still have one branch every 2 versions or when there is too much change)

Did you experiment your approach on some repo ?
