### ISSUE TITLE
[RFC] README.rst generator

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintainer-tools#335]
This follows #295 and a discussion with @elicoidal while working on the mis builder documentation.

Currently the README.rst is created manually by module authors. It contains 
- a mix of hand-written information (description, usage, credits, etc), 
- boiler plate OCA text (eg reference to OCA maintainers, link to runbot, link to issue tracker),
- some information that is redundant with the manifest (eg license badge)

The current situation makes it difficult to maintain consistency across OCA addons in the boilerplate text. It also makes it difficult to ensure consistency between the manifest and the README (eg for the license badge and the upcoming development status).

This is a proposal to let authors write the relevant text in small files and have the README.rst be generated nightly.

# Proposal

Let authors create reStructuredText fragments in the addon root directory,:
- introduction.rst
- installation.rst (optional)
- configuration.rst (optional)
- usage.rst
- developer.rst (optional, developer instructions)
- roadmap.rst (optional, known issues, future ideas)
- contributors.rst (optional)
- credits.rst (optional, additional credits other than authors and contributors)
- history.rst (optional, the changelog)

Each rst fragment should be composed of body text (paragraph, lists, tables, images) and *must not* contain any section title.

Create a new script `oca-gen-addon-readme` that generates README.rst for each addon in a repo where introduction.rst and usage.rst are present. The sections content is drawn from the rst files. Section titles are not generated if the corresponding rst file is absent. Title, license badge and development status badge are obtained from the addon manifest. If introduction.rst or usage.rst is missing, README.rst is left unchanged.

Update the nightly job that updates repos README.md to invoke `oca-gen-addon-readme` too.

**Comment by sbidoul** [comment]
I just updated the text above to move the fragments to the addon root directory. This is to avoid issues when the docs directory is used to contain a sphinx documentation like @guewen does in [connector](https://github.com/OCA/connector/tree/11.0/connector/doc).

**Comment by max3903** [comment]
Is it possible to also generate an index.html in the description directory?

**Comment by sbidoul** [comment]
> README should not be regenerated if no change happened

Of course

> add a section developer (optional) 

done

> introducing CONTRIBUTORS.rst and AUTHORS.rst

My current thinking is that it's more flexible to let people write the whole credit section the way they please (except the maintainer part which will be generated). So they can add special credits (funders, thanks to my mom, etc) if they want to.

I'm also wondering if we should generate part of the README from the `authors` manifest key.

**Comment by sbidoul** [comment]
> Is it possible to also generate an index.html in the description directory?

Yes, this opens up the possible to have a nicer presentation than what Odoo currently does when displaying the readme. That require a bit more thinking because people may want to keep control on the index.html to provide a more customized display.

**Comment by elicoidal** [comment]
@sbidoul Why am thinking about AUTHORS+CONTRIBUTORS file is because for the repository documentation (aggregated) we might end up with a mess if we do not restrict/limit the content of this files.

**Comment by elicoidal** [comment]
Maybe we need an additional `credit` file for other purposes (founders etc...)

**Comment by sbidoul** [comment]
> Maybe we need an additional credit

Ok, I added contributors.rst and credits.rst. Authors would come from the manifest.

**Comment by elicoidal** [comment]
> That require a bit more thinking because people may want to keep control on the index.html to provide a more customized display.

Do we need some kind of configuration checkbox somewhere? `Auto-generate README.rst` and `Auto-generate HTML description` (or better the opt-out one). Easy to do in the ERP with the github interface but looks complicated to maintain though

**Comment by sbidoul** [comment]
> Auto-generate README.rst

This would be implicit as soon as introduction.rst and usage.rst are present. 

I'd keep index.html generation for a second phase.

**Comment by lmignon** [comment]
@sbidoul I like you proposal. The generation of the 'index.html' file could help us to solve the annoying bug with images not properly displayed at same time into github, appstore and odoo/settings/modules https://github.com/odoo/odoo/issues/8300

**Comment by dreispt** [comment]
Why multiple rst files instead of a single description.rst with multiple sections?

**Comment by elicoidal** [comment]
@dreispt the idea is to be able to combine the files into a README file for each module AND into a manual for the repository: this is why we need one file per section or concept in order to aggregate them properly at intermediate or higher level

**Comment by elicoidal** [comment]
@OCA/board we should move quickly on this one and allocate resources on the generation script

**Comment by dreispt** [comment]
@elicoidal My concern is that we could be making contributions harder. 
Could it be more effective to have all the intended sections in only two or three text files?

Suggestion:

- description.rst
    - introduction
    - installation (optional)
    - configuration (optional)
    - usage
- development.rst
    - developer (optional, developer instructions)
    - roadmap (optional, known issues, future ideas)
    - contributors (optional)
    - credits (optional, additional credits other than authors and contributors)
    - history (optional, the changelog)

**Comment by dreispt** [comment]
OK, sounds reasonable.
The current README boilerplate is  big contribution turnoff (for me, at least).

**Comment by elicoidal** [comment]
In terms of aggregation I would prefer to have a CONFIGURATION.rst apart. It makes more sense in a manual to have all configuration part together and all usage together. I wont block for that though.

For the INSTALLATION.rst, it is barely used, most of it could be boiler plate (pip install or docker). Same goes for DEVELOPER which is mostly used for specific advise and technical modules: what about merging DEVELOPERS and INSTALLATION into TECHNICAL?

**Comment by elicoidal** [comment]
LGTM.
One question/thought: as INSTALLATION might be barely used and should be standard, why not drop it and have another section MISC.rst as catch-it-all?

**Comment by sbidoul** [comment]
I'm not sure where a MISC section would fit in the README structure? Yet installation may be useful when, for instance, there are external non python packages to install.

**Comment by elicoidal** [comment]
Non essential to me but just to cover the unknown case today

**Comment by dreispt** [comment]
The INSTALLATION section is very rarely needed.
IMO, for the rare cases is it needed, it would be appropriate to include that information in the CONFIGURATION info.

**Comment by pedrobaeza** [comment]
On OCA/website-themes#4, there has been a discussion around an index.html file for better app store visibility. Do you think we can include here this generation as well?

**Comment by sbidoul** [comment]
@pedrobaeza I've pushed an static/description/index.html on mis bulider 10 (generated from README.rst using rst2html). Let's see how it looks like when it reaches apps.odoo.com.

**Comment by sbidoul** [comment]
@pedrobaeza it [looks good](https://apps.odoo.com/apps/modules/10.0/mis_builder/). I'll do another PR for that.

**Comment by pedrobaeza** [comment]
Great! Is the script already running every night? I suppose you have used the "OCA Git Bot" for commiting this, isn't it? I will include instructions in the migration guide for skipping these commits when doing `git -am` and start modifying modules to the new structure.

And we should make also a communication (blog post + mail on contributors list) about this great achievement IMO.

**Comment by sbidoul** [comment]
> Great!

Actually the look is [slightly better with README.rst](https://apps.odoo.com/apps/modules/10.0/mis_builder_budget/). But can still generate index.html and see if we can tune the style later.

> Is the script already running every night? 

Not yet

> used the "OCA Git Bot" for commiting this

yes

> communication (blog post + mail on contributors list

absolutely

**Comment by pedrobaeza** [comment]
> Actually the look is slightly better with README.rst. But can still generate index.html and see if we can tune the style later.

Maybe we can include some CSS styling?

**Comment by elicoidal** [comment]
Can Valera help? cc @max3903

**Comment by max3903** [comment]
@elicoidal Not much. She is busy and this is simple css we can do quicker.

**Comment by sbidoul** [comment]
@elicoidal nothing urgent anyway, it's not that bad.
