### ISSUE TITLE
Typo in wiki 'Migration to version 11.0'

### ISSUE THREAD

**Issue by r12213** [OCA/maintainer-tools#347]
Not really a big deal, but there is a typo in 'Migration to version 11.0' wiki.

In 'Tasks to do in the migration' section:

- `report.external_layout_header`: the same as above, but looking inside `<div class="footer o_background_footer"> `element.

should be:

- `report.external_layout_footer`: the same as above, but looking inside `<div class="footer o_background_footer"> `element.

**Comment by pedrobaeza** [comment]
Thanks for mentioning. Changed!
