### ISSUE TITLE
README.rst generator addings

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-tools#351]
@sbidoul what do you think about adding these things:

* The general translated percentage widget for the header, and the detailed one by language according https://translation.odoo-community.org/widgets/l10n-spain-11-0/
* Restore the details about the module in the link for creating a new issue.

**Comment by elicoidal** [comment]
The summary one is a very good idea: I would not add the full one: just make it a target link for the summary

**Comment by pedrobaeza** [comment]
But the summary doesn't say anything meaningful...

**Comment by sbidoul** [comment]
I also think showing the status of all translations is not ideal for the readme.

How about this: https://github.com/OCA/maintainer-tools/pull/353 ?

**Comment by pedrobaeza** [comment]
And what about the other idea of re-adding the complete link new issues (for doing both together and not generating more update commits)?

**Comment by sbidoul** [comment]
@pedrobaeza about the issue creation link, it was removed a while ago in #180. Do you want it back?

**Comment by pedrobaeza** [comment]
I'm not talking about the issue/PR templates (which I don't know why it were removed also...), but the link for creating a new issue in the README file.

Example:
https://github.com/OCA/l10n-spain/blob/8.0/account_balance_reporting/README.rst
`https://github.com/OCA/l10n-spain/issues/new?body=module:%20account_balance_reporting%0Aversion:%208.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**`

It was removed because it was very difficult to be maintained manually, but now that this is automatic...

**Comment by sbidoul** [comment]
@pedrobaeza like this? #354

**Comment by pedrobaeza** [comment]
Yes, exactly!

**Comment by dreispt** [comment]
@pedrobaeza There is a [Bug Tracker](https://github.com/OCA/mis-builder/tree/10.0/mis_builder#bug-tracker) section with the link to Issues.
Github now allows you to setup Issue templates in the repository configurations.
