### ISSUE TITLE
README generator - Including more than one maintainer manifest is making travis fail

### ISSUE THREAD

**Issue by lreficent** [OCA/maintainer-tools#364]
When specifying more than one maintainer in the manifest, the README is generated perfectly but you end with a failed travis build. See: [ddmrp manifest](https://github.com/OCA/ddmrp/blob/11.0/ddmrp/__manifest__.py#L14), [readme](https://github.com/OCA/ddmrp/tree/11.0/ddmrp#maintainers) and [last travis build](https://travis-ci.org/OCA/ddmrp/jobs/411096984#L540)

cc @sbidoul @jbeficent

**Comment by sbidoul** [comment]
@lreficent can you test https://github.com/OCA/maintainer-tools/pull/365?

**Comment by lreficent** [comment]
yes, let me include it in a open PR and see the result.

**Comment by pedrobaeza** [comment]
No need of that, I'm fast-tracking as I know that this is the correct fix.

**Comment by lreficent** [comment]
Great! Thanks for the fast response! :+1:
