### ISSUE TITLE
New module and manifest possibilities for v12

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-tools#366]
According to @yelizariev's tweet https://twitter.com/yelizariev/status/1026427096451563521, there seems to be changes on the modules kanban view for adding more info. We should adapt our tools and maybe guidelines to adapt them to this.

https://github.com/odoo/odoo/commit/4ed7690d43

cc @OCA/board

**Comment by simahawk** [comment]
so what's the proposal? Shall we link straight to the module path on github?
The only issue might be to include the version into it but we could have an extra linter checking that if we have a version in there it matches the major one in module's version.

**Comment by pedrobaeza** [comment]
No noticeable changes to be taken into account IMO, so I close.
