### ISSUE TITLE
RFC: Module versioning, automatic forward/backward ports

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-tools#381]
I recently discovered https://mergify.io, which is a GH bot that automatically merges PRs when they reach some requirements, and [it can even also create automatic backports](https://doc.mergify.io/automated-backport.html).

This can be a good workaround to OCA's maintenance problem explained at #334, and can be very helpful.

Example workflows it could simplify:

- When a new branch is released (such as recently 12.0), it could automatically forward port each addon and merge it if tests pass.
- One would only need to care about opening PR to the latest version, backports would be automatic.
- Maintainers would only need to approve PR. When all rules are OK, it would get merged automatically.

Besides, it's free for open source projects, and has a python FOSS engine at https://github.com/Mergifyio/mergify-engine.

Thoughts?

**Comment by moylop260** [comment]
LGTM
What about runbot odoo bot since that we could avoid auto-merging code with sql-injection and so on?

**Comment by sbidoul** [comment]
Automatic merging based on rules is trivial to implement in [OCA/oca-github-bot](https://github.com/oca/oca-github-bot), so I'd prefer to see a PR there to implement that (with an issue first to discuss and agree on the rules beforehand).

Automatic back/forward ports, I'm not sure it would work on our multi-addons repos, but one could try.

In general though we must be very careful when adding more tools, as the maintenance of all those tools connected to our hundreds of OCA repos is become more and more of a burden as we grow.

And our multi-addons repos and processes have many specificities that might not be covered by a generic bot, so yeah, I'd prefer getting inspiration from existing bots and implementing them in a codebase we control and we can all see what's going on and make evolve with our own community processes.

**Comment by Yajo** [comment]
Both points seem legit.

We already discussed in person the pain on maintaining an increasing number of code bases, with their divergencies. Actually the idea should be that human-made patches are made just once, and the bot handles the ports.

Should we then move this conversation to oca-github-bot instead?

**Comment by Yajo** [comment]
Oh, another question: For keeping ports automatically installable, one OCA guideline should change: we shouldn't prefix module versions with odoo versions.

Odoo makes that automatically after all, and it would give merge conflicts in basically every port. BTW, porting an addon and resetting its version to "X+1.0.1.0.0" is confusing because it seems like the addon for newer odoo version is older or viceversa...

OK with that too? :thinking:

**Comment by pedrobaeza** [comment]
Each module version evolves different on each version. Doing that, we will end up having very high numbers, like 14.0.20.1.0. And the conflict is not solved with that. You will have the same conflict as the previous part is different: 11.0.1.0.0 vs 12.0.1.0.0.

The solution for this is to have a bot for bumping module version. Any way, as @sbidoul confirms that no bump is required for pypi when deploying with `--pre`, I have abandoned the requirement of asking for bumping module version.

**Comment by Yajo** [comment]
Since we use `module_auto_update`, the version is also meaningless for us.

> You will have the same conflict as the previous part is different: 11.0.1.0.0 vs 12.0.1.0.0.

That would be the case today, but as ports keep happening, and conflicts keep getting solved, the problem may disappear in the future, little by little.

**Comment by pedrobaeza** [comment]
@Yajo the problem can't disappear if you keep the main version there, as the diff file will be:
```diff
- 'version': '11.0.1.0.0'
+ 'version': '11.0.1.0.1'
```
And we shouldn't remove the `11.0` part

**Comment by Yajo** [comment]
> we shouldn't remove the `11.0` part

That's exactly what I was asking for. Why can't that be removed?

**Comment by pedrobaeza** [comment]
Because it was agreed as the main way to know that the module is on that version and not other. I also prefer to stick to that version. The bumping version bot should be the way to go IMO.

**Comment by lmignon** [comment]
AFAIK the odoo version part is also used by setuptools-odoo...  We must preserve it since it also adds a strong semantic into the version scheme. 

IMO the bot to bump the version is not the way to go. Bumping the version must be under the responsibility of the addon's maintainer. Depending of the changes merged into the master branches, he can choose to create a major/minor/patch version. The creation of a new version is also a strong signal that the end of a development cycle for the addon.

**Comment by pedrobaeza** [comment]
@lmignon, but if we instruct the bot to bump version as requested, we isolate real diff from version bump. I though this was already discussed as a good balance.

**Comment by Yajo** [comment]
> AFAIK the odoo version part is also used by setuptools-odoo... We must preserve it since it also adds a strong semantic into the version scheme.

I'm not aware of setuptools-odoo internals, but you can take inspiration from the way Odoo evaluates module versions for migrations. [It's an interestingly simple 4-line function](https://github.com/odoo/odoo/blob/5822d3cbdb19288271a2b36613c44a678fa14cc1/odoo/modules/migration.py#L115-L118). I'm pretty sure it would be very easy to fix.

> Because it was agreed as the main way to know that the module is on that version and not other

Then possibly that agreement should be reevaluated, it seems to be introducing more problems than benefits. I might be missing some, but see both lists :thinking: :

Pros:

- "to know that the module is on that version and not other": Present OCA convention is to remove code for new Odoo branches. Go see the repos' 12.0 branches; they're almost empty. So, we already have a way to know the module is on that version: if it exists in that branch.

  In the case of older branches, there's the `installable: False` that indicates the same.

  So, no, there's no benefit here.

:thinking: I'm not able to find any ~~other~~ benefit, TBH, besides the fact of not having to change current agreed workflow.

Cons:

- When migrating an addon, you must update the version to match odoo's version. Rutinary useless work.
- When migrating an addon, the addon code versions diverge, so you now don't have a way to know if the addon `12.0.1.0.0` will have the features and fixes it had before when it was `11.0.7.3.1`. At first sight, it might seem like yes (12 > 11, isn't it?), but when you are aware on our versioning convention, you realize that the first 2 numbers mean actually nothing (well, the Odoo version, but that would be automatically added if missing), so... is the v12 addon older? Less maintained? Yikes! It's confusing.
- When doing backward/forward ports, you *always* will get a conflict. As a human, it's disturbing. As a bot, it's a real problem. An unnecessary problem, BTW.
- You lose the ability of doing [multi-odoo-version migration scripts](https://github.com/odoo/odoo/blob/5822d3cbdb19288271a2b36613c44a678fa14cc1/odoo/modules/migration.py#L65-L69). Since your versioning schema is unrelated across odoo versions, you always have to use [odoo-release-specific migration scripts](https://github.com/odoo/odoo/blob/5822d3cbdb19288271a2b36613c44a678fa14cc1/odoo/modules/migration.py#L71-L73). It impacts on maintainability and confusion. Like before, as humans, confusing; as a bot, a very hard to solve problem.

---

As a side reflection, if our maintainability plan is such a mess that it becomes almost impossible to automatize, that's a clear indicator of a deep design problem. By making life easier for bots, we will automatically make it easier for us! :robot: :heart: 👨‍💻

---

ping @OCA/core-maintainers, I'd love to hear opinions here on the matter.

**Comment by lmignon** [comment]
> I'm not aware of setuptools-odoo internals, but you can take inspiration from the way Odoo evaluates module versions for migrations. It's an interestingly simple 4-line function. I'm pretty sure it would be very easy to fix.

At first glance I don't see how setuptools-odoo could easily know this version of odoo. This is valid for any other script that would need to know for which version an addon is developed. 
It is not possible, nor healthy to rely on the branch name because sources can be managed in different vcs...
Should we imagine a new key in the manifest? I'm not for it.
The problem mentioned here is the automatic forward port.... One solution could be to exclude version dump commits from the forward port mechanism.

**Comment by sbidoul** [comment]
Hi all, here are a few thoughts on the version numbering question:
- I also suffer from merge conflicts on the version
- I find it nice to know the supported Odoo series by looking at the addon version
- On the modules I maintain I try to have the last 3 digits more or less aligned across Odoo series to express feature level
- setuptools-odoo as `odoo_version_override` to cover cases where the Odoo series cannot be discoverd in the manifest version, but it's never used so far (we could use it if really needed)
- git has a concept of merge filter, I'm wondering if it could be used to automatically resolve such conflicts

**Comment by simahawk** [comment]
To me odoo version should not be part of the module version (yes, I hate those conflicts too!).

OTOH we must be able to understand at glance that the module is for odoo version XX.
Would it be hard/troublesome to have another key in the manifest?

It's going to be ignored ATM by odoo itself (as @Yajo [pointed out](https://github.com/odoo/odoo/blob/5822d3cbdb19288271a2b36613c44a678fa14cc1/odoo/modules/migration.py#L115-L118) they add it automatically if not present).
The oca bot can read it and use it to do its maintenance stuff (pypi releases, etc)

We now have automatic README generation: we can make it prominent in the README.

Another option, if we want to keep manifest clean, could be to have a separated file (ie: $module/ODOO_VERSION) but this might be harder to catch especially for newcomers.

Side note, I agree with:

> On the modules I maintain I try to have the last 3 digits more or less aligned across Odoo series to express feature level

I think we should discuss / re-discuss the policy here: resetting the versions from odoo version to another makes harder to understand what feature/fix is here and there.

**Comment by simahawk** [comment]
BTW shall we change the title of this issue to: "RFC on module version and merge policy"? :smile:

**Comment by sbidoul** [comment]
Note if we add a manifest key, it should not be written far from version line, otherwise we'll still have merge conflicts. There must be a better way.

**Comment by Yajo** [comment]
Thank you all for your comments. At least it seems we agree that **this is a real problem**.

>  It is not possible, nor healthy to rely on the branch name because sources can be managed in different vcs...

But... Why? I mean, we can use an environment variable or whatever we want to get that info, and use git as a fallback, but as of today, all of our CI tools extract the odoo info from the branch AFAIK (runbot, travis...). Odoo apps does the same, so what's the problem?

> One solution could be to exclude version dump commits from the forward port mechanism.

This assumes that version bumps are done in separate commits, but that's not much the case as of today.

> OTOH we must be able to understand at glance that the module is for odoo version XX.


It seems to me that you assume that users use the manifest version to know the addon is supported or not; am I right?

However, IMHO no user will ever look at a manifest. I think that the main place where a user will go search if an addon exists for his odoo version is https://www.odoo.com/apps, where it has colorful badges that indicate that stuff:

![captura de pantalla de 2018-10-15 10-42-36](https://user-images.githubusercontent.com/973709/46943237-1f4aba00-d067-11e8-949d-3c74c5b6d418.png)

Odoo uses the git branch for that info, and It's pretty clear already. 

For us, OCA devs, which live in Github, it's something clear too:

![captura de pantalla de 2018-10-15 10-55-48](https://user-images.githubusercontent.com/973709/46944072-0c38e980-d069-11e8-8d0d-e0f9f0e81211.png)


So why do we care so much of making clear _something that's already clear_?


> Would it be hard/troublesome to have another key in the manifest?

That would make sense, had we only one master branch where to support many odoo versions, but that :v: crazy :v: idea has been widely rejected by Odoo and OCA.

So, with this alternative approach, I think that it doing it:

- would lead to diff troubles also and we'd end up at the same place we are now
- Makes me wonder: should we then indicate in module's version for odoo 9 that it supports odoo 11?

  Doesn't make much sense, right :thinking: . It should only indicate if it works or doesn't work, and that comes from the `installable` key that already exists and is well supported everywhere. 🤷‍♂️

> git has a concept of merge filter, I'm wondering if it could be used to automatically resolve such conflicts

I don't think so. I mean, that could work, but then we'd have still the same problem: If the latest version of an addon is `12.0.3.1.5`, and we are backporting it to odoo 11, we don't want it to ignore that diff; we want it to bump it to `11.0.3.1.5`. I doubt Git can do that.

**Comment by dreispt** [comment]
IMHO:

Major version in the module version is useful: if you find code files outside VCS you will know the target version.

Automatic PRs with forward ports of fixes would be useful. They at least create a "task to do", and the could will should be adapted and merged; at worst they are useless and will be closed by maintainers if pointless. If a bot can create them, surely it won't be hard for it to also update the forward port version numbers also.

It would be nice to experiment this in a couple of selected repos.

**Comment by pedrobaeza** [comment]
Creating a PR with the port instead a direct commit can alleviate a bit the problem, but will create another: a lot of opened PRs (and more when we have more versions) that most of the times won't be interesting.

**Comment by lmignon** [comment]
> Creating a PR with the port instead a direct commit can alleviate a bit the problem, but will create another: a lot of opened PRs (and more when we have more versions) that most of the times won't be interesting.

IMO it's not a problem if we have a way to specify on the addon if the bot must take care to create PRs for forward/back ports. Is such a way it becomes of the maintainer responsibility to activate or not the bot for the addons he/she maintains.

**Comment by pedrobaeza** [comment]
Yeah, that can be another option.

**Comment by pedrobaeza** [comment]
@elicoidal I think you have taken my point. You will have a conflict of versioning when developing simultaneous diverge features on 2 versions.

**Comment by sbidoul** [comment]
@Yajo look at [Defining a custom merge driver](https://git-scm.com/docs/gitattributes#_performing_a_three_way_merge)

So yes, it is possible to implement a merge driver that is smart enough to ignore changes to the first 2 parts of the version in the manifest.

**Comment by elicoidal** [comment]
> I think you have taken my point.

Actually I think the opposite. If the major version is present I am OK to start from current version number at migration. It means that yes if you have to have features in the previous version, you might continue increasing  with a number identical to the new version or even moving forward but for me it is not important as long as there is a major version to differentiate. Without major version, I fully agree with you @pedrobaeza that it can quickly become a mess

**Comment by Yajo** [comment]
> IMO it's not a problem if we have a way to specify on the addon if the bot must take care to create PRs for forward/back ports. Is such a way it becomes of the maintainer responsibility to activate or not the bot for the addons he/she maintains.

Mergify allows to use labels to control the bot behavior: https://doc.mergify.io/examples.html#using-labels-to-backport-pull-requests

---

So, everyone (except me :laughing:) agrees that having the odoo version in the module manifest is useful to know it's available for such version?

But, what if we do this, that was already commented by @simahawk?:



> We now have automatic README generation: we can make it prominent in the README.

It seems we'd have the human-readable necessary info, in the human-readable part of the code, while still forgetting about confusing versioning and unnecessary git conflicts? :thinking: 

We can even have a beautiful label for that: ![](https://img.shields.io/badge/odoo-11.0-green.svg)

Would this be an acceptable alternative?

**Comment by simahawk** [comment]
:+1: for the readme label
:+1: for controlling via PR labels

**Comment by NL66278** [comment]
IMHO automatic merging is very dangerous and might mess up modules by introducing incompatible changes. As for version numbers: I am totally with @pedrobaeza on this. The modules made for each major Odoo version have their own evolution (reflected in the minor/patch version), dependent on the needs of integrators. Back or forward porting features will also be done on the basis of need, but in my opinion can not safely be automated.

**Comment by pedrobaeza** [comment]
@Yajo can we close this?

**Comment by Yajo** [comment]
I guess...
