### ISSUE TITLE
class="page" -> class="article"

### ISSUE THREAD

**Issue by bfig** [OCA/maintainer-tools#387]
### Milestone (Odoo version)
-  11

Hello,

Just wanted to thank you all guys for the migration guides in the wiki. I want to add something to the v11 guide where I wasted a lot of time and is not reflected: the report layouts have been changed, and class="page" is not working anymore (v11 enterprise in .sh). Now it needs to be class="article".

Hope it helps,

Best regards,
Bruno

**Comment by pedrobaeza** [comment]
That's not true. Class is working the same way. For example:

https://github.com/odoo/odoo/blob/55899f849acd213efa8ddd59d1b0eedc187d460c/addons/account/views/report_invoice.xml#L7

You have to check your customizations.
