### ISSUE TITLE
Discrepancy between doc and module template on how XML files should be named

### ISSUE THREAD

**Issue by luisg123v** [OCA/maintainer-tools#388]
According to [the documentation](https://github.com/OCA/maintainer-tools/blob/9766529146bcb61ce746623da74a23163199bdd3/CONTRIBUTING.md#user-content-file-naming), XML files should be named without suffix, i.e. data/`res_partner.xml`, `views/res_partner.xml`, etc.

However, if we check the module template, we'll notice  it's with suffix for [data](https://github.com/OCA/maintainer-tools/blob/9766529146bcb61ce746623da74a23163199bdd3/template/module/data/model_name_data.xml), [demo](https://github.com/OCA/maintainer-tools/blob/9766529146bcb61ce746623da74a23163199bdd3/template/module/demo/model_name_demo.xml) and [views](https://github.com/OCA/maintainer-tools/blob/9766529146bcb61ce746623da74a23163199bdd3/template/module/views/model_name_view.xml).

To solve this, I see three possibilities:
1. Modify the documentation to match the template
1. Modify the template to match the documentation
1. Modify the documentation to encourage both alternatives

**Comment by pedrobaeza** [comment]
Thanks for bringing this to table.

Yes, this is a discrepancy. For me, we should go for option 1, as the suffix is important when you are looking for file name, so the suffix gives you the rest of the information.

**Comment by luisg123v** [comment]
@pedrobaeza  
I personally prefer option 2, because I find the suffix redundant. However, since I'm aware the community prefers option 1, I'll go for that approach instead.

I know there were already a discussion regarding this topic, but I couldn't find it.

CC @moylop260

**Comment by luisg123v** [comment]
Here is the PR: https://github.com/OCA/maintainer-tools/pull/389
