### ISSUE TITLE
Github labels for non maintainers users

### ISSUE THREAD

**Issue by yvaucher** [OCA/maintainer-tools#39]
The problem is well describded here:
https://github.com/neovim/neovim/issues/1409

It would be great to let people label them-selves their PR when it needs review or when they consider it to be WIP.

Here is path we could follow by using a bot to auto-assign labels depending on PR titles:
https://github.com/neovim/bot-ci/pull/28

To note, actually labels are automatically removed when a PR is merged. This is done by Waffle.io

**Comment by sbidoul** [comment]
@yvaucher if you want to have a try with oca-github-bot, do not hesitate :)

WIP example here: https://github.com/OCA/oca-github-bot/pull/1

**Comment by pedrobaeza** [comment]
Implemented i the other repo, so closing.
