### ISSUE TITLE
Migrating modules: script to delete views

### ISSUE THREAD

**Issue by rousseldenis** [OCA/maintainer-tools#390]
We recently had migration issues on how some OCA modules were migrated.

In fact, when deleting views, we have to point attention that inherited view maybe does not exist in new major version.

As the view entry exists in db, Odoo will try to load it before deleting it (and breaks) when executing -u all.

So, IMHO we have to add a line in migration process to pay attention on that. What do you think ?

**Comment by pedrobaeza** [comment]
Right now, OpenUpgrade v11 deactivate views that can't be rendered. There are exceptions like assets definition (it's happening on the renaming of `account_financial_report_qweb` to `account_financial_report`, but I think they can be treated manually. Any way, other suggestions are welcome.

**Comment by pedrobaeza** [comment]
I'm seeing that the feature is present in:

* 9.0: #1288
* 10.0: #1311
* 11.0: #1313

so it's weird that it's not deactivated. I will check later the specific example you give in the PR.

**Comment by pedrobaeza** [comment]
Next time, I think it's better to put this kind of things directly in OCA/OpenUpgrade.

**Comment by rousseldenis** [comment]
@pedrobaeza Ok, that sounds good. But quite tricky.

**Comment by pedrobaeza** [comment]
@rousseldenis one thing I'm now seeing: this is only valid with custom views, which means that they are views without XML-ID. Your error is because the view belongs to a module. They should be removed by the upgrade process normally, but I don't know why not in this case.

**Comment by rousseldenis** [comment]
Error on my side. Didn't catch previous step errors. But if you don't use OpenUpgrade and do a module update, process breaks (haven't tested)

**Comment by pedrobaeza** [comment]
It should be similar, as Odoo update process removes non existing views in your module.
