### ISSUE TITLE
CLAbot weird error

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-tools#394]
@gurneyalex there's something weird with the CLAbot. Check the comment https://github.com/OCA/stock-logistics-workflow/pull/470#issuecomment-439114618.

It says my colleague is not found in the CLAs. First thing I have checked is that commits are with the proper email:

![seleccion_009](https://user-images.githubusercontent.com/7165771/48589200-dd998180-e93a-11e8-8c23-42f82111984d.png)

and you can see also that GitHub recognizes them with the GitHub profile `sergio-teruel`.

![seleccion_010](https://user-images.githubusercontent.com/7165771/48589278-22bdb380-e93b-11e8-8f6f-3ebe474cf764.png)

and finally, on OCA instance the contact is properly setup:

![seleccion_011](https://user-images.githubusercontent.com/7165771/48589303-3ec15500-e93b-11e8-8647-a4714653fc7d.png)

so I don't have any clue on what's going on.

Can you please check?

**Comment by gurneyalex** [comment]
@pedrobaeza could there be 2 partners in our database with the same github login, one without a CLA ?

**Comment by pedrobaeza** [comment]
No, I tried that also. Sorry for not mentioning.

**Comment by lreficent** [comment]
Similar issue here: https://github.com/OCA/product-attribute/pull/399#issuecomment-434381089

**Comment by gurneyalex** [comment]
I'll look into this today

**Comment by pedrobaeza** [comment]
Maybe this is because the mail is not public and CLAbot is not able to deduce the github login from the commit information?

**Comment by gurneyalex** [comment]
My analysis of the issue : it seems that on the PR, the github login of some of the commits is lost. It may be related to rebase or rebase merge or cherry pick, I'm not sure. In these cases the clabot is not fetching the correct information. I'm working on a fix.

**Comment by pedrobaeza** [comment]
OK, thanks for the followup

**Comment by gurneyalex** [comment]
@pedrobaeza  Discussion on the fix at https://github.com/OCA/oca-github-bot/pull/22

**Comment by pedrobaeza** [comment]
Closing as merged.
