### ISSUE TITLE
readme generator generates different output depending on docutils version installed

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintainer-tools#423]
Exemple:

```html
<meta name="generator" content="Docutils 0.15.1: http://docutils.sourceforge.net/" />
```

This is annoying because an accidental docutils upgrade (it is not pinned in maintainer-tools setup.py) can trigger a regenaration of all readme index.html, with the useless republishing of a ton of packages to pypi, and hours of travis builds.

First we should pin docutils to 0.15.1 in maintainer-tools setup.py with a comment explaining why.

This solution will break at some point because inevitably, in the future, that specific version will end up being not installable or too old for some other dependency...

**Comment by pedrobaeza** [comment]
Isn't any way (arg or similar) to avoid to stamp that meta tag?

**Comment by sbidoul** [comment]
Yes we could remove that line. But the whole thing remains very sensitive to small changes in the html output produced by docutils.

That index.html is only there because Odoo SA

**Comment by pedrobaeza** [comment]
Yeah, good point about other possible changes due to different versions. Pinning seems a good option. Indeed, the HTML stuff is something very annoying...
