### ISSUE TITLE
Accounting version 13.0

### ISSUE THREAD

**Issue by i-vyshnevska** [OCA/maintainer-tools#430]
This issue should gather information for changes in accounting between v12 and v13
to update wiki page https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0
fields renaming, replacing, other model, moving functional between methods

**Comment by i-vyshnevska** [comment]
account.invoice -> account.move
        reference - ref
        partner_bank_id - invoice_partner_bank_id
        line_ids - related to account.move.line
        invoice_line_ids - changed relation from account.invoice.line to account.move.line, filtered field to line_ids
        tax_line_ids - was relation on account.invoice.tax, now account.invoice.tax replaced on account.tax, previous functions relies on tax_repartition_line_id which linked to new model
        
account.invoice.line -> account.move.line
account.invoice.tax -> account.tax

Views:
        All invoices form account.view_move_form they differ just on "type" of it
        account.invoice_form -> account.view_move_form
        account.invoice_supplier_form -> account.view_move_form

**Comment by pedrobaeza** [comment]
I have added a reference to this issue in the migration guide for not saturating it with lots of data, so I close the issue now for not being outstanding. Thanks for the insights.

**Comment by luisg123v** [comment]
Hi @i-vyshnevska,

I'd like to add to this issue, so maybe you could edit your comment if I'm not wrong.

I think the field `reference` on the invoice refers to the payment reference, which is stored on the move on `invoice_payment_ref`, not `ref`. The field `ref` would be filled with the `name` AFAIK.

Here is the list I've compilated so far to translate field names of invoices:
- `name` -> `ref`
- `origin` -> `invoice_origin`
- `move_name` -> `name`
- `comment` -> `narration`
- `payment_term_id` -> `invoice_payment_term_id`
- `source_email` -> `invoice_source_email`
- `reference` -> `invoice_payment_ref`
- `sent` -> `invoice_sent`
- `date_due` -> `invoice_date_due`
- `date_invoice` -> `invoice_date`

And for invoice lines:
- `invoice_id` -> `move_id`
- `uom_id` -> `product_uom_id`
- `invoice_line_tax_ids` -> `tax_ids`

CC @hugho-ad @moylop260

**Comment by i-vyshnevska** [comment]
also helpfull info 
https://github.com/OCA/OpenUpgrade/blob/13.0/addons/account/migrations/13.0.1.1/openupgrade_analysis.txt

**Comment by gaikaz** [comment]
The commit of the whole thing with a good description: https://github.com/odoo/odoo/commit/beaa30a3d1843de43a45f419bfbc1bfa7613a920

**Comment by carmenbianca** [comment]
For posterity's sake, here's the PR that created the commit linked by @gaikaz : https://github.com/odoo/odoo/pull/33797
