### ISSUE TITLE
Migration to version 13.0 

### ISSUE THREAD

**Issue by BIZ4Africa** [OCA/maintainer-tools#433]
### Milestone (Odoo version)
- 13.0 

### Module(s)
- hr_employee_relative

**Comment by sbidoul** [comment]
Hello @BIZ4Africa 

If you are migrating this module, you should mention it as a comment in https://github.com/OCA/hr/issues/683.

I'll therefore close this issue which does not belong to this repo. Let me know if you meant something else.
