### ISSUE TITLE
oca-gen-addon-readme: No image path substitution on inline images

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-tools#439]
One example is https://raw.githubusercontent.com/OCA/social/12.0/mail_tracking/readme/USAGE.rst

**Comment by pedrobaeza** [comment]
@legalsylvain you were the original author of this useful feature. Can you please check?

**Comment by legalsylvain** [comment]
Hi @pedrobaeza : 

Seems to be an error of regexpr. But testing your use case, it seems that the expression is correct.
I tested on the plateform https://regexr.com/

``.*`` should catch the ``|delivered|`` pattern.

![image](https://user-images.githubusercontent.com/3407482/69955949-1634da80-14ff-11ea-824b-6ceb825fb0ed.png)

Not an expert on that point, sorry. maybe @acsone team could take a look? 

regards.

the regexpr is here : https://github.com/OCA/maintainer-tools/blame/42ac1fd0ec1a648bc9baa578f759f63c4046385e/tools/gen_addon_readme.py#L149

**Comment by pedrobaeza** [comment]
Thanks for the insights. Waiting for more feedback to see if we can fix it.

**Comment by sbidoul** [comment]
The replacement were correctly done for the README in the OP example: https://github.com/OCA/social/blob/12.0/mail_tracking/README.rst?plain=1

So closing. Feel free to re-open if there are other issues.
