### ISSUE TITLE
Migration to 13.0 wiki page, github reference link can not find commit

### ISSUE THREAD

**Issue by bodedra** [OCA/maintainer-tools#445]
### Current paragraph

Check that all "compute" methods of non-stored computed fields assign a value in any case to the field, even if it is a falsy one. 

click on click.

![Firefox_Screenshot_2020-03-31T08-24-58 333Z](https://user-images.githubusercontent.com/14229503/78004141-585c1480-7357-11ea-875c-849f451d98fd.png)

It will give me following output.

![Firefox_Screenshot_2020-03-31T08-25-19 979Z](https://user-images.githubusercontent.com/14229503/78004180-63af4000-7357-11ea-81b2-649408bb8776.png)

### Correct link:

https://github.com/odoo/odoo/commit/2e43bfc1c4b2f61e0459614f61f90a77dc3b7233

**Comment by pedrobaeza** [comment]
As that's still a PR, I have removed the link and keep the guideline.
