### ISSUE TITLE
[13.0][WIKI] Update tasks to do

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/maintainer-tools#449]
In the section **Tasks to do in the migration** I miss the following:
* Change all field attributes `track_visibility='onchange'` by the field attribute `tracking=True`.

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

**Comment by pedrobaeza** [comment]
But `track_visibility='onchange'` is still admitted, isn't it?
