### ISSUE TITLE
[RFC][IMP] gen_addons_table : Add maintainers and maturity columns

### ISSUE THREAD

**Issue by legalsylvain** [OCA/maintainer-tools#454]
Hi all, 

I was thinking about the possiblity to update the gen_addons_table script, to add two new columns : 

- a Maintainers column with the list of the maintainers as set in each module readme file. ([Sample](https://github.com/OCA/mis-builder/tree/10.0/mis_builder#maintainers))
- a badge column, with the maturity level (alpha, beta, ...) as set also in each module readme file([Sample](https://github.com/OCA/mis-builder/tree/10.0/mis_builder#mis-builder))

What do you think ? 

It could help to : 
- have an overview of the unmaintained modules ; 
- have an overview of the modules maturity ;

thanks for your feedback. CC : @sbidoul, @pedrobaeza

**Comment by pedrobaeza** [comment]
As you know, I don't like too much that table, as it adds a lot of noise in commits and require the scanner that updates it, but if you have it, the maintainer can be interesting (if updated, which not always is true), and the maturity is as well, but people doesn't care too much about this unfortunately, so most of them will show beta.

**Comment by sbidoul** [comment]
Hi Sylvain, I think it's a good idea to give a better visibility to these two important concepts. I'd put the maturity badge inside the version cell to save some space.
