### ISSUE TITLE
[WIKI] Migration to version 12.0 - broken link

### ISSUE THREAD

**Issue by mymage** [OCA/maintainer-tools#458]
Link to https://www.odoo.com/es_ES/slides/slide/let-s-create-records-faster-602 seems broken.

**Comment by pedrobaeza** [comment]
Changed in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0/_compare/cd2dc9aaf6ca64dc1db6aef528a10612a10ab822...a71213aaf67e8f725203a1e5cfef128b7587c9ff for the Youtube video, as the slide is no longer available.
