### ISSUE TITLE
oca-gen-addon-readme: Title level inconsistent using `~`

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-tools#459]
Using the following PR:
 - https://github.com/OCA/server-tools/pull/1776

Running the following command:
 - `oca-gen-addon-readme --repo-name=server-tools --branch 13.0 --org-name=OCA --addon-dir=server-tools/sentry`

The file output is:
 - 
https://gist.github.com/moylop260/97cece8c80ca4c6ed168ae38704c42df

RST check output is:
```txt
docutils.utils.SystemMessage: /tmp/tmpmm_bwpc7/sentry/README.rst:160: (SEVERE/4) Title level inconsistent:

Authors
~~~~~~~
```

I just googled a little bit and I found the following answer:
 - https://stackoverflow.com/a/24504437

Should we change `-` instead of `~`?

**Comment by moylop260** [comment]
Hi @sbidoul @legalsylvain 
What do you think?

**Comment by sbidoul** [comment]
@moylop260 Only `~` is allowed as title underlines in README fragments, so there is no need to change. See also https://github.com/OCA/maintainer-tools/pull/455#issuecomment-636305924.
