### ISSUE TITLE
Abandon python 2.7 support in maintainer-tools

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintainer-tools#476]
Can we stop testing for python 2 support in maintainer-tools ?

I'd say it's fairly reasonable to request maintainer-tools users to install it with python 3.6+ nowadays.

Where it is used in oca-github-bot and pre-commit hooks it is already python 3.

**Comment by pedrobaeza** [comment]
Agree

**Comment by sbidoul** [comment]
Done in #477

**Comment by lmignon** [comment]
:+1:
