### ISSUE TITLE
Automate part of XML migration to v14

### ISSUE THREAD

**Issue by Daemo00** [OCA/maintainer-tools#478]
Hi all,
this is not really an issue, I just happened to create a Python script for automating a part of the XML migration to v14 and wanted to share it.
Specifically, the script is https://gist.github.com/Daemo00/69599e023fa519061feb1863f620ab6b and helps substituting `act_window` and `report` tags with `record` tag.

The script can surely be improved, feel free to edit it and some better version can maybe be included in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0 to help migration of existing modules.

### Milestone (Odoo version)
- 14.0

### Steps to reproduce
1. Migrating a module to 14.0 (following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0)

### Current behavior
Manual substitution of `act_window` and `report` tags due to:
```
DeprecationWarning: The <act_window> tag is deprecated, use a <record> for {xml_id!r}
```

### Expected behavior
Automatic substitution

**Comment by pedrobaeza** [comment]
This may fit in https://github.com/OCA/odoo-module-migrator/

**Comment by Daemo00** [comment]
Thanks I didn't know that repo, I'll try to move the script in there.

Maybe https://github.com/OCA/odoo-module-migrator/ could be mentioned in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0 (and other Migration* wikis)?

**Comment by pedrobaeza** [comment]
It has been moved very recently, and I don't know it very well, so I haven't been able to provide a good documentation to be included. If you do, maybe you can pass us some paragraphs to add.

**Comment by Daemo00** [comment]
@pedrobaeza I have proposed https://github.com/OCA/odoo-module-migrator/pull/38, so we can close this _issue_.

As for https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0, turns out I don't know how to propose a change :sweat_smile:: I have cloned https://github.com/OCA/maintainer-tools.wiki.git locally but can't manage to create a fork for it, then I can't create a PR.

The closest thing I've managed is https://github.com/OCA/maintainer-tools/compare/master...Daemo00:recommend_migrator,
but `git` correctly tells me that the histories of `maintainer-tools` and `maintainer-tools.wiki` are unrelated so that doesn't allow for a PR.

As you can see I'd only add a line with a link to the new repo, I think there are already enough instructions for using the new tool in the repo's `README`.

**Comment by pedrobaeza** [comment]
Yes, I'm afraid GitHub doesn't still allow to propose changes through regular mechanism. What you can do is to open an issue with such content and let any of the maintainers of the repo (including me) to add the text.
