### ISSUE TITLE
ERROR: Requested docutils<0.15.1.1,>=0.15.1 (from oca-maintainers-tools==0.1.dev998+g1b5c7ad) has different version in metadata: '0.15.1'

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-tools#485]
Help, I see 14.0 build failing because of oca-maintainers-tools.
Example: https://travis-ci.com/github/OCA/account-analytic/jobs/457559449#L299

**Comment by pedrobaeza** [comment]
Fixed in #483 and waiting for its deployment by @sbidoul
