### ISSUE TITLE
repo search-engine is missing

### ISSUE THREAD

**Issue by pniederlag** [OCA/maintainer-tools#488]
### Steps to reproduce
1. run oca-clone-everything

### Current behavior

failure on cloning search-engine

```
Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
fatal: Kein Git-Repository: 'search-engine/.git'
```

other repos did checkout fine

### Expected behavior

all listed projects checkout

**Comment by simahawk** [comment]
search-engine seems to be listed https://github.com/OCA/maintainer-tools/blob/master/tools/oca_projects.py#L179 
Do you still have this issue?
