### ISSUE TITLE
Just to be said

### ISSUE THREAD

**Issue by yvaucher** [OCA/maintainer-tools#49]
Couldn't we rename this repo "maintainer-tools" ?

Each time I search something
in maintainer-quality-tools
 or
in maintainer**s**-tools

it bother me.

Am I the only one?

**Comment by dreispt** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Yes, please!

This must be done by any member with permissions

**Comment by max3903** [comment]
Done!
