### ISSUE TITLE
Migration to version 15.0: --directory option added

### ISSUE THREAD

**Issue by BernatPForgeFlow** [OCA/maintainer-tools#518]
WIKI

@pedrobaeza 
Hello Pedro!

On the wiki of the migration to version 15, why did you add the option **--directory $MODULE**?
@GuillemCForgeFlow and me are using the command with this new option but we don't understand the functionality with the addition:
It creates an additional leftover directory with the same name as the module, that is not necessary. Without this option, it was working correctly.    

![Captura de pantalla de 2021-11-17 12-31-33](https://user-images.githubusercontent.com/90243017/142193262-7ba8856c-cb30-4d3e-85be-da67da2ee4ae.png)

**Comment by pedrobaeza** [comment]
I added because if not, for me it's not working the command. Maybe it depends on the version of `git`? Which one do you have?

**Comment by pedrobaeza** [comment]
Sorry, `it's not working` means that the contents of the module are put in the root folder instead of the module folder.

**Comment by BernatPForgeFlow** [comment]
We are using **git version 2.25.1**

**Comment by BernatPForgeFlow** [comment]
Okay, we understand. We will use it without your option.

**Comment by pedrobaeza** [comment]
I'm using the exact same version, so it's very weird... Maybe I'm the only one with the problem. I'm reverting the change in the migration guide until being sure.
