### ISSUE TITLE
[gen-addon-readme] Add support of runboat

### ISSUE THREAD

**Issue by rousseldenis** [OCA/maintainer-tools#524]
@sbidoul @gurneyalex

**Comment by sbidoul** [comment]
Yes, you can do a PR if you like.

This depends on #520 for deployment.

**Comment by pedrobaeza** [comment]
Well, basically all READMEs will change, so no need of #520, isn't it?

**Comment by sbidoul** [comment]
There is no strong need to regenerate all READMEs since the redirection to runbot is in place.
And we still need #520 to avoid a regeneration of everything each time we want to tweak the README for any reason .

**Comment by pedrobaeza** [comment]
OK, I prefer to have the new shiny badge "Try me on runboat", but as you prefer.

**Comment by sbidoul** [comment]
This will be done as part of #564
