### ISSUE TITLE
[Wiki] migration from 12.0 to 13.0

### ISSUE THREAD

**Issue by obayit** [OCA/maintainer-tools#532]
In the wiki, in the part that says:

> Remove multi field from ir.actions.act_window models. Now you have binding_view_types field for indicating in which view the action will be available: list, form or empty for both. If declaring the action through the accelerator tag <act_window>, then use the attribute binding_views. More reference in https://github.com/odoo/odoo/pull/24738/commits/33d51480688065e367eb646f12b89d721749cac9.

In the `act_window` in version `11.0` ther was an attribute `src_model` I think in `13.0` it has changed to `binding_model`.

This note should be added to the wiki, since the error when doing the upgrade is not helping, it just says invalid xml schema.
 
Also there is no `key2` attribute anymore

**Comment by pedrobaeza** [comment]
Thanks for noting it. Added in the wiki.
