### ISSUE TITLE
Update our tooling to support Odoo 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintainer-tools#537]
What needs to be done to create the 16.0 branches
- [x] determine python and posstgres version to use in CI
  - Odoo SA's runbot is on python 3.10
  - It seems the jsonb translations require postgres 12+
- [x] prepare migration wiki page https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0
- [x] create OCB 16.0 branch @pedrobaeza 
- [x] update [OCB sync script](https://github.com/OCA/maintainer-tools/blob/master/tools/ocb-sync.sh) @pedrobaeza - https://github.com/OCA/maintainer-tools/pull/538
- [x] deploy updated OCB sync script @sbidoul
- [x] update click-odoo and click-odoo-contrib (needed to generate .pot files with click-odoo-makepot) @sbidoul
  - https://github.com/acsone/click-odoo/pull/51
  - https://github.com/acsone/click-odoo-contrib/pull/120
- [x] setuptools-odoo - to publish wheels @sbidoul
  - support Odoo 16 https://github.com/acsone/setuptools-odoo/pull/83/commits/31cc5ba784e783b4275c0a63f7abc4e6945df055
  - declare the minimum supported python version @sbidoul https://github.com/acsone/setuptools-odoo/pull/93
- [x] request new PyPI classifier https://github.com/pypa/trove-classifiers/pull/117 by @sbidoul 
- [x] manifestoo / manifestoo-core (used by oca-ci) @sbidoul
- [x] [oca-ci](https://github.com/oca/oca-ci) - to test with GitHub actions https://github.com/OCA/oca-ci/pull/37 by @carmenbianca 
- [x] ~Update MQT~ (likely not necessary anymore)
- [x] update [addons repo template](github.com/oca/oca-addons-repo-template) https://github.com/OCA/oca-addons-repo-template/pull/160 by @lmignon 
- [x] ~update [oca-github-bot](github.com/oca/oca-github-bot)~ nothing to do
- [x] restart oca-github-bot to pick-up latest build tools @sbidoul
- [x] update runboat config @sbidoul
- [x] generate 16.0 branches (oca-create-branch) @sbidoul
- [x] create migration issues (oca-create-migration-issue) @sbidoul
- [x] update weblate deployment [Dockerfile](https://github.com/OCA/oca-weblate-deployment/blob/master/Dockerfile) to use latest maintainer-tools @sbidoul https://github.com/OCA/oca-weblate-deployment/commit/bc81fa46c63e8c8a7ba4460e9f291cb00abc3806
- [x] deploy weblate
- [x] in OCA Odoo Instance, add the new series in GitHub > GitHub Comunity > Organizations > OCA.
- [ ] create 16.0 OpenUpgrade branch
- [ ] create branches on apps.odoo.com

See #509 for links to similar PRs for 15.0.

**Comment by pedrobaeza** [comment]
I can create the OCB 16.0 branch

**Comment by legalsylvain** [comment]
Hi @sbidoul, could you add : 
- [ ] create 16.0 OpenUpgrade branch ? (the project has to be created manually)

**Comment by pedrobaeza** [comment]
OCB branch created: https://github.com/OCA/OCB/tree/16.0

**Comment by pedrobaeza** [comment]
And the OCB sync script updated at https://github.com/OCA/maintainer-tools/pull/538

**Comment by carmenbianca** [comment]
I'll have a look at oca-ci.

**Comment by sbidoul** [comment]
If anyone wants to try updating the repo template, that is welcome as I have little available time this week.
Mostly, we need to pick-up the latest linters (doing a dry-run of `pre-commit autoupdate` on an existing repo will give the versions to use), and determine which pylint-odoo rules to make mandatory, and the new ones to enable.

**Comment by lmignon** [comment]
@sbidoul I'll take a look at the repo template.

**Comment by lmignon** [comment]
oca-addons-repo-template PR: https://github.com/OCA/oca-addons-repo-template/pull/160

**Comment by lmignon** [comment]
looking at [oca-github-bot](https://github.com/oca/oca-github-bot), the only thing that would need to be changed is the config on the server in the environment file to add version 16.0 in MAINTAINER_CHECK_ODOO_RELEASES

**Comment by lmignon** [comment]
IMO the topics `determine python and postgres version to use in CI` and `update [addons repo template](https://github.com/OCA/maintainer-tools/issues/github.com/oca/oca-addons-repo-template)` can be ticked as done. 
For the record I manually created the [16.0 branch](https://github.com/OCA/rest-framework/tree/16.0) on the rest-framework repo and created a [first PR](https://github.com/OCA/rest-framework/pull/291) to check that [runboat](https://runboat.odoo-community.org/webui/builds.html?repo=oca/rest-framework&target_branch=16.0) works as expected with odoo 16.0. -> :champagne:

**Comment by pedrobaeza** [comment]
Should we proceed with the 16.0 branches creation? @sbidoul are you going to do like other years?

**Comment by sbidoul** [comment]
I'll do it yes. I was planning to do it this weekend if everything is ready.

Last open question I think is the pylint configs: https://github.com/OCA/oca-addons-repo-template/pull/160#issuecomment-1258552425

**Comment by sbidoul** [comment]
I prepared OCA/social: https://github.com/OCA/social/issues/974. All looking good.
Still waiting a little bit for input about pylint-odoo before opening all other repos.

**Comment by TheMule71** [comment]
Hi. I don't really know how to propose changes to Wiki pages (the edit buttton escapes me), so I'm gonna add a comment here.

IMHO the following items are worth considering as additions to the guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0:

- https://github.com/odoo/odoo/commit/26b2472f4977ccedbb0b5ed5f08be2c04313fd21 changes to `account.account`: `account.account.type` model is no more, now `account_type` is a selection field.
- https://github.com/odoo/odoo/commit/d8d47f9ff8554f4b39487fd2f13c153c7d6f958d accounting v16 - refactoring of `@onchange` methods. Some synchronization methods have been removed, there's less need to explicitly call methods to recompute `account.move` internals when making changes from python
- https://github.com/odoo/odoo/commit/23483865b1508346f5a5e178f4a436fe1a9d9f55 some fields became HTML from Text - this may affect you if you read/write them in python code

**Comment by pedrobaeza** [comment]
Hi, Marco, I'm afraid GitHub doesn't still offer any way to do such suggestion (or that seems so - https://stackoverflow.com/questions/10642928/how-can-i-make-a-pull-request-for-a-wiki-page-on-github).

Anyway, the changes we put there are the framework ones, not the data model ones, as this last category is very long (see https://github.com/OCA/OpenUpgrade/pull/3583 for the whole list of changes), and it will lose the focus of the guide, as you may not need to know those changes to make the migration (it depends on what are you touching).

**Comment by TheMule71** [comment]
Makes sense, thanks.
