### ISSUE TITLE
Permissions in github

### ISSUE THREAD

**Issue by alejandrosantana** [OCA/maintainer-tools#54]
I was able to edit this project wiki just a few moments ago. It was for a fix (a typo in PEP8 url link) and  with good spirit, of course, but... Is it supposed that way? As I am not in the members list, can anyone edit it?

Just to avoid any future problem.

**Comment by alejandrosantana** [comment]
@max3903 or @guewen , anything on this? To avoid 
Also, is there a list of mantainers? Should be within this very project, right? Or in every project README.

**Comment by max3903** [comment]
@alejandrosantana I will move the conventions in the project repo later this week

**Comment by alejandrosantana** [comment]
OK!
