### ISSUE TITLE
Module Migration from v15 to v16

### ISSUE THREAD

**Issue by HarhuTechnologies** [OCA/maintainer-tools#542]
**Is your feature request related to a problem?**
There are some modules missing to be migrate and I want to migrate them.

**Module Migration**
I want to migrate all the remaining modules from v14 to v15, v15 to v16

**Describe alternatives you've considered**
I want the list of modules to be migrate for specific version so I can start work on it.

**This is our start with OCA, we are newbie**
I need a help of team to guide to contribute to OCA

**Comment by pedrobaeza** [comment]
Hi, when you have the pull request of the module migration and CIs pass, a command put by any PSC will add the module to the migration issue. Please see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 (or the corresponding version one) for tips about the procedure, and if the jump is between several versions, just change the numbers on the command fetching the commits).

**Comment by pedrobaeza** [comment]
Closing as no direct issue in the modules.

**Comment by jcdrubay** [comment]
The list of modules to migrate to version 15 can be found here:
https://oca-cm-15.komit.link/odoo-module-versions
