### ISSUE TITLE
[IMP] Migration to version 16.0 WIKI - web.assets_qweb deprecation

### ISSUE THREAD

**Issue by chienandalu** [OCA/maintainer-tools#546]
Proposed check list item:

- XML assets templates are now added into regular asset bundles. Previously they were added to the fake asset bundle `web.assets_qweb` and now they should be should be declared in their proper assets bundle that fit their scope (`web.assets_backend`, `web.assets_frontend`, etc). You can check plenty of examples in the original refactor: https://github.com/odoo/odoo/pull/95500

**Comment by chienandalu** [comment]
ping @pedrobaeza

**Comment by pedrobaeza** [comment]
Included in the wiki, thanks.
