### ISSUE TITLE
[IMP] Migration to version 15.0 WIKI - xml-deprecated-tree-attribute

### ISSUE THREAD

**Issue by chienandalu** [OCA/maintainer-tools#548]
- Remove the `string` attribute from `<tree>` tags. They're deprecated as the name for the view in UI is given by the `act_window` that loads it. Review any `act_window` name that is launched dinamically by a python method; their name attribute should be a translatable string.

cc @Tecnativa 

ping @pedrobaeza

**Comment by pedrobaeza** [comment]
But I think this is something from before, not on v15. It's just that v15 now is verbose about this.

**Comment by chienandalu** [comment]
Sure, it goes back to version `8.0`... Closing then as pre-commit enforces it already.
