### ISSUE TITLE
unaccent migration guideline is in the wrong version wiki

### ISSUE THREAD

**Issue by chienandalu** [OCA/maintainer-tools#549]
This point should belong to the 16.0 guidelines and not to the 15.0 one as it is now.

- Put `unaccent=False` on field definitions where no distinction should be made between accented words, for getting better performance on searches. Example: `parent_path` field. See https://github.com/odoo/odoo/pull/76436 for more details.

**Comment by pedrobaeza** [comment]
Changed.
