### ISSUE TITLE
isort version to be increased

### ISSUE THREAD

**Issue by KKamaa** [OCA/maintainer-tools#553]
## Module
Current version of maintertools

## Describe the bug
Hey guys I saw that we havent update maintainer-tools isort version which leads to the error described [here](https://github.com/PyCQA/isort/pull/2078)

## To Reproduce
**Current Version**: just take OCA branch 16.0 and try using pre-commit on it.

1. Get an OCA branch version 16.0
2. using the maintainer-tools try running `pre-commit run -a`
3. error pops

**Expected behavior**
`pre-commit` run needs to run without errors so the soln is to update the **.pre-commit-config.yaml** isort to new version e.g > 5.12.0

**Additional context**
So its an isort upgrade issue, latest isort will fix the error

**Comment by pedrobaeza** [comment]
This was tackled in https://github.com/OCA/oca-addons-repo-template/pull/184.

**Comment by pedrobaeza** [comment]
Do `pipx run copier -f update` for upgrading the repo to latest copier template and do a PR fixing it.
