### ISSUE TITLE
About squashing bot commits

### ISSUE THREAD

**Issue by SirTakobi** [OCA/maintainer-tools#559]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
Bots commit should be squashed in the commit that originated them.

**Describe alternatives you've considered**
THere is a guide in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate, but either I haven't understood it completely, or there is something to fix in the example, here the example:
> ```
> 4c88180 (contributor1) [ADD] module_x
> 2a0f1de (OCA-git-bot) [UPD] README.rst
> 21fede3 (oca-travis) [UPD] Update module.pot
> 83526e8 (oca-transbot) Update translation files
> 00d0e95 (translator1) Translated using Weblate (Italian)
> b112d0c (contributor2) [FIX] module_x: Fix README explanation
> a437b38 (OCA-git-bot) [UPD] README.rst
> 19891ab (translator1) Translated using Weblate (Italian)
> f31004c (translator2) Translated using Weblate (Italian)
> 5a3fc49 (translator2) Translated using Weblate (Spanish)
> 922d16b (contributor2) [IMP] module_x: Add a new feature
> 8f90d6c (oca-travis) [UPD] Update module.pot
> ```

[...]

> This would be the result for the example:
>
> ```
> pick 4c88180 (contributor1) [ADD] module_x
> f 2a0f1de (OCA-git-bot) [UPD] README.rst
> f 21fede3 (oca-travis) [UPD] Update module.pot
> f 83526e8 (oca-transbot) Update translation files
> pick 00d0e95 (translator1) Translated using Weblate (Italian)
> f 19891ab (translator1) Translated using Weblate (Italian)
> pick b112d0c (contributor2) [FIX] module_x: Fix README explanation
> f a437b38 (OCA-git-bot) [UPD] README.rst
> pick f31004c (translator2) Translated using Weblate (Italian)
> pick 5a3fc49 (translator2) Translated using Weblate (Spanish)
> pick 922d16b (contributor2) [IMP] module_x: Add a new feature
> f 8f90d6c (oca-travis) [UPD] Update module.pot
> ```

I am looking at commit `19891ab`: it has been created after `b112d0c`, and it is fixed-up in `00d0e95`.
Shouldn't it be picked after `b112d0c`? It might be translating something that has been introduced in `b112d0c`, so I don't understand how it can be moved before that commit.

**Additional context**
I can't propose any change to the wiki in the wiki repository because when trying to fork, I obtain:
> ❯ gh repo fork --remote-name SirTakobi        
failed to fork: HTTP 404: Not Found (https://api.github.com/repos/OCA/maintainer-tools.wiki/forks)

There is a proposal for automating this procedure in https://github.com/OCA/odoo-module-migrator/pull/41.

**Comment by pedrobaeza** [comment]
Yes, it's moved on purpose. There can be 2 scenarios:

- The translations have been done in 2 time slots. Why being separated then?
- The translations have been done because there's a change in the code. Anyway, why keep them split if they come from the same author?

There's a possibility of not being able to do such squash if the code changes include translation modifications, but on that case, the process will abort and then you know that you can't do that.
