### ISSUE TITLE
Bug No package metadata was found for oca-maintainers-tools  when generating readme file

### ISSUE THREAD

**Issue by mourad-ehm** [OCA/maintainer-tools#563]
I try this "oca-gen-addon-readme --repo-name=account-invoicing --branch=16.0 ...".
And I got this bug:
`Traceback (most recent call last):
  File "/home/mourad/maintainers-tools/env/local/bin/oca-gen-addon-readme", line 33, in <module>
    sys.exit(load_entry_point('oca-maintainers-tools', 'console_scripts', 'oca-gen-addon-readme')())
  File "/home/mourad/maintainers-tools/env/local/bin/oca-gen-addon-readme", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for oca-maintainers-tools
`
Is there any known issue?

**Comment by pedrobaeza** [comment]
Did you install it following the procedure specified in the readme with pipx?

**Comment by pedrobaeza** [comment]
Well, use the other one...

**Comment by mourad-ehm** [comment]
I have other problems with the other one. I'll try to solve it. Thanks

**Comment by rousseldenis** [comment]
> I have other problems with the other one. I'll try to solve it. Thanks

Yes, the pipx install is definitely the good way to do it. If you have problems with it, don't hesitate to share, we can maybe help
