### ISSUE TITLE
OCA icon not showing on READMEs

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-tools#57]
There is a problem with OCA logo referenced (http://odoo-community.org/logo.png) in the README files, that makes it to not show up.

@gurneyalex or any board member, can you check it?

**Comment by yvaucher** [comment]
Not shown on github

i.e. https://github.com/OCA/purchase-workflow/tree/8.0/purchase_requisition_bid_selection

But visible on app.odoo.com

i.e. https://www.odoo.com/apps/modules/8.0/purchase_requisition_bid_selection/

**Comment by pedrobaeza** [comment]
Do you know why?

**Comment by yvaucher** [comment]
No idea. It is strange that badges images are loaded but not the OCA image.

It could be an issue with github rst interpreter.

**Comment by pedrobaeza** [comment]
Maybe image format. Can you try to resave the image to see?

**Comment by yvaucher** [comment]
I don't have the necessary access rights. What I can see in html is this:

<img alt="Odoo Community Association" src="https://camo.githubusercontent.com/47828635b5c9032c08c4c6c3db92dcc8299c5fa3/687474703a2f2f6f646f6f2d636f6d6d756e6974792e6f72672f6c6f676f2e706e67" data-canonical-src="http://odoo-community.org/logo.png" style="max-width:100%;">

And going to https://camo.githubusercontent.com/47828635b5c9032c08c4c6c3db92dcc8299c5fa3/687474703a2f2f6f646f6f2d636f6d6d756e6974792e6f72672f6c6f676f2e706e67

Leads to nothing.

**Comment by yvaucher** [comment]
Just found this
https://help.github.com/articles/why-do-my-images-have-strange-urls/

**Comment by yvaucher** [comment]
shouldn't the url be https ?

**Comment by yvaucher** [comment]
This was somehow solved. I close this issue
