### ISSUE TITLE
Add a new CONTEXT section into README.rst

### ISSUE THREAD

**Issue by TumbaoJu** [OCA/maintainer-tools#571]
As part of the project to include / attract more functional people into contributing to OCA modules, there have been discussions around the use of the Read me and how functionals could be contributing at modules documentation.

One of the ideas / needs for functional people is to be able to document the context, some use cases, the why of the module.

So, we came with the idea of adding a new file/section to the Read Me dedicated to this topic.

It could be named : **Context/Use cases**

It could be added after the _Description_ but before the _Installation_.
![Proposal_add_section_read_me](https://user-images.githubusercontent.com/38360781/235539404-f693ba2e-ed2a-416d-8ee6-2810085a7c3d.png)

**Comment by TumbaoJu** [comment]
@sbidoul : Here is the issue for the proposal of the new Read Me section

**Comment by pedrobaeza** [comment]
I'm not sure about adding a new section instead of putting the business use case inside DESCRIPTION.rst, which is the most visible one and most of the times is equivalent and the explanation is blended with the rest of the description. See for example https://github.com/OCA/sale-workflow/pull/2473/files#diff-630cc9f3ce79965b50eee70bf1e7247de551fb31fa5eafe8cd05a71e02998c34R28

**Comment by francesco-ooops** [comment]
Hi @pedrobaeza, 

being "Description" the first visible part of the readme, I think it would be good if we could keep it as concise and direct as possible, explaining immediately "what" the module does;

"Usage" should then explain "how" the goal in description is achieved;

"Context/Use Cases" would be a space (also) for functionals to go in depth of the "why" one should employ this module. 

IMHO it wouldn't be ideal to have too long of a "Description" section; I think @TumbaoJu request has the goal of adding a space where functionals can find and contribute module documentation without making the main description too lengthy.

**Comment by pedrobaeza** [comment]
I think the description is the best suitable place, but my opinion is only one amongst a lot, so if the rest wants to go that direction, OK for me.

**Comment by sbidoul** [comment]
Missing use case is often my main complaint concerning OCA documentation. Too often I contemplate a module, more or less understanding what it does but wondering when to use it.

So I'm in favor of encouraging contributors to add context / use case information.

I also think the description part must remain concise. I don't know if use case information would often be too long for the description section.

One interesting benefit of a separate CONTEXT  fragment is that it opens the possibility to enforce its presence in 17.

**Comment by sbidoul** [comment]
I propose #576 to implement this.
