### ISSUE TITLE
About squashing translation commits

### ISSUE THREAD

**Issue by SirAionTech** [OCA/maintainer-tools#580]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
An improvement to the documentation in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate.

Sometimes there are consecutive commits from the same author saying
> [Added translation using Weblate (Italian)](https://github.com/OCA/l10n-italy/pull/3392/commits/2b686b05e9fd4b5b8e1541d4359c64e4b9ab8bac)
> [Translated using Weblate (Italian)](https://github.com/OCA/l10n-italy/pull/3392/commits/5daca0db9600ea7c5b3375138c8d2014e9986597)

I think it would be ok to squash them together, can this use-case be added to the documentation?

**Comment by pedrobaeza** [comment]
Included here: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests/_compare/61aed2771fc607b79318071455c2079203ac6686...01d0f4767ca6daa402e1dc0c3e2be526aa0df035

**Comment by SirAionTech** [comment]
Thanks
