### ISSUE TITLE
Update migration v17 Wiki

### ISSUE THREAD

**Issue by rven** [OCA/maintainer-tools#591]
Following part should be added to the Wiki

* The `attrs` and `states` attributes are no longer used.
  * Replace in views by `invisible`, `required` or `readonly`

  A warning will be issued if not replaced. Check the framework change and replacement examples at https://github.com/odoo/odoo/pull/104741.

**Comment by rven** [comment]
@pedrobaeza

**Comment by pedrobaeza** [comment]
Added in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0/_compare/0a6f2eaf0c17a7917f465217c456f03f98cb94be...efb0b4e6c3966dded8b4e9f76dba652796129436

Thanks for the reference.
