### ISSUE TITLE
Update wiki "Migration to version 16.0" with `fields_view_get` becomes `get_view`

### ISSUE THREAD

**Issue by cuongnmtm** [OCA/maintainer-tools#598]
https://github.com/odoo/odoo/commit/b03c227e885efa4ccdcad43ccb56ee10371b9284

> If using `fields_view_get()` method to adjust the view, now use the method `get_view()`.

**Comment by cuongnmtm** [comment]
I think this sentence can be placed after the line below

 > If using `fields_get_keys()` method for ...

**Comment by pedrobaeza** [comment]
Done at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0/_compare/24b846c1af3072150e390a6ecaa8c53694365e36...c025d9fb6b9342fb865bb82f241e54646ee98b8e

Thanks.
