### ISSUE TITLE
pandoc-3.2-1-amd64.deb added by precommit hook

### ISSUE THREAD

**Issue by gurneyalex** [OCA/maintainer-tools#619]
Is it intended that the precommit hooks add [pandoc-3.2-1-amd64.deb](https://github.com/OCA/operating-unit/pull/667/files#diff-c64b58dd76f52ba2c9e8b7d0818f8c4d2e9f732788ec8b650df70762c852ddd1) to the repositories? 

I've seen this multiple time in PR reviews, and I'm wondering if this is intentional, or a blooper.

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/oca-addons-repo-template/issues/262

**Comment by gurneyalex** [comment]
Thanks for the pointer :)

**Comment by pedrobaeza** [comment]
Closing this as redirected to the other issue.

**Comment by sbidoul** [comment]
I propose to keep this open, as there is a fix to do in both projects. Actually, in the project template, the .gitignore workaround of Alexandre should be sufficient, but we want to fix it here too.

**Comment by nilshamerlinck** [comment]
- created https://github.com/OCA/maintainer-tools/pull/620
- there's less than a dozen branches impacted branches for now, I would vote for a manual:
  - `$ git filter-repo --path pandoc-*.deb --invert-paths --refs 17.0`
  - force push
  - rebase on weblate side
- open PRs will also have to rebase :/
