### ISSUE TITLE
Update command in the migration section for wiki "Migration to version 17.0".

### ISSUE THREAD

**Issue by RodrigoBM** [OCA/maintainer-tools#621]
I propose to change the command `git checkout -b 17.0-mig-$module origin/17.0` for this other one which is more recommended `git switch -c 17.0-mig-$module origin/17.0`

**Comment by pedrobaeza** [comment]
Why is it more recommended? Which git minimal version is required?

**Comment by RodrigoBM** [comment]
It was added in version 2.23, but it is true that it is still experimental.
But from what I've read it will be the recommended way to create new branches.

- https://medium.com/dev-genius/forget-git-checkout-use-git-switch-and-git-restore-78fb01a55011
- https://git-scm.com/docs/git-switch

I close issue and will recommend it when it is no experimental.
