### ISSUE TITLE
CONTRIBUTING.md: some typos

### ISSUE THREAD

**Issue by tafaRU** [OCA/maintainer-tools#83]
I see in this section https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#pep8-options:

```should adhere to PEP8 and PyFlakes standards standards```

I assume this part of sentence is wrong but I don't know what it is the right one. Perhaps @bwrsandman could you help me in order to make a proper PR.

**Comment by bwrsandman** [comment]
Double `standards` you can take one out directly from the interface
![screenshot from 2015-07-17 14-45-42](https://cloud.githubusercontent.com/assets/1013356/8754594/a79cb236-2c92-11e5-84ef-e5f9370759c4.png)

**Comment by tafaRU** [comment]
Thanks @bwrsandman
