### ISSUE TITLE
Including the description template in the contributing

### ISSUE THREAD

**Issue by elicoidal** [OCA/maintainer-tools#85]
What about we include the standard description template in the guideline. I am not sure where though
(keeping it as an example as below so people know how to use it)

.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
    :alt: License: AGPL-3

Get back sales orders to draft
==============================
[Short description of you module
eg: Allows to get back to draft any cancelled sale order.]

Installation
============

Nothing special is needed to install this module.

Configuration
=============

Nothing special is needed to configure this module.

Usage
=====

When you cancel a sale order, you will see a new button call *Back to draft*,
that resets the sale order to draft state.

Known issues / Roadmap
======================

None known.

Bug Tracker
===========
[Where to post bug and issues
eg: Bugs are tracked on `GitHub Issues <https://github.com/OCA/sale-workflow/issues>`_.
In case of trouble, please check there if your issue has already been reported.
If you spotted it first, help us smashing it by providing a detailed and welcomed feedback
`here <https://github.com/OCA/sale-workflow/issues/new?body=module:%20sale_order_back2draft%0Aversion:%208.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_.
]
Credits
=======

Contributors
------------

* Contributor1 <mail>
* Contributor2 <mail>

Maintainer
----------

.. image:: https://odoo-community.org/logo.png
   :alt: Odoo Community Association
   :target: https://odoo-community.org

This module is maintained by the OCA.

OCA, or the Odoo Community Association, is a nonprofit organization whose
mission is to support the collaborative development of Odoo features and
promote its widespread use.

To contribute to this module, please visit http://odoo-community.org.

**Comment by guewen** [comment]
The template is here: https://github.com/OCA/maintainer-tools/tree/master/template/module
A link could be added in the guidelines.

**Comment by pedrobaeza** [comment]
I prefer to include the link

**Comment by dreispt** [comment]
+1 for the link

**Comment by elicoidal** [comment]
a link sounds good

**Comment by pedrobaeza** [comment]
It has been done, so it can be closed.
