### ISSUE TITLE
[REF] contributing: What with .pot file in i18n/ folder?

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-tools#97]
Now with the use of transifex... is unnecesary to add .pot file in i18n of modules.
The question is: What should be our guideline?
A) File .pot required in each module of oca.
B) Don't add .pot file never.
C) You can choose if add .pot file or not.

What do you think?

**Comment by pedrobaeza** [comment]
Option C can be, because having the .pot file is not a blocking issue (although the script will regenerate it)

**Comment by dreispt** [comment]
.pot and .po files should be allowed: contributors can provide modules already with some translations, and thats a good thing.

**Comment by pedrobaeza** [comment]
@dreispt We are talking specifically for pot files, that are auto-generated. po files indeed are allowed to provide translations directly without the use of Transifex.

**Comment by qtheuret** [comment]
I'm for Option C

**Comment by max3903** [comment]
C

**Comment by moylop260** [comment]
Ok, I got it
Thank you.
Then you can choose if add `.pot` file or not.
Then we don't need to add a new conventions for that.
I close this issue.

**Comment by pedrobaeza** [comment]
My opinion on this have changed since the issue, because I found somebody translating from an outdated POT file. I prefer now to remove entirely POT files (option B).

**Comment by sbidoul** [comment]
Let's keep the issue open, since there is also an ongoing discussion on the mailing list?

**Comment by osvalr** [comment]
My option is C
Just because it will be replaced anyways and most developers will be adding (or modifying) it

**Comment by pedrobaeza** [comment]
This is now outdated as new Weblate requires POT and PO. Closing.
